; -- Platform specific build flags
[esp32s3]
extends = esp32
board_build.mcu = esp32s3

build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
    -D LOG_MAXIMUM_LEVEL_VERBOSE
    -D LOG_DEFAULT_LEVEL_WARNING
    ; -D LOG_TIMESTAMP_SOURCE_SYSTEM
    -D CONFIG_ARDUHAL_ESP_LOG=5
    ;-D CONFIG_LOG_COLORS=1
    -I include    ; include lv_conf.h and hasp_conf.h
    -I ${PROJECT_DIR}/src/
    ; -- littlevgl build options ------------------------------
    -D LV_USE_FS_ARDUINO_ESP_LITTLEFS=1     ; Use builtin Arduino LittleFS
    -D ESP32_HW
    -D VER_MAJ=0
    -D VER_MIN=0
    -D VER_REV=1
    ; -DCORE_DEBUG_LEVEL=5
    -D LOG_LOCAL_LEVEL=5 ; Verbose
    -D ARDUINO_LOOP_STACK_SIZE=8192
    ;-D HASP_VER_REV=4-rc1
    ${override.build_flags}

ps_ram =
    -DBOARD_HAS_PSRAM
    ;-D HASP_USE_FREETYPE=1
    ;-D LV_USE_FREETYPE=1
no_ps_ram =
    ;-D HASP_USE_FREETYPE=1
    ;-D LV_USE_FREETYPE=1

; -- The Arduino ESP32 v2.0.2 with 3 available flash sizes:
[arduino_esp32s3_v2]
extends = esp32s3
framework = arduino
; platform = https://github.com/tasmota/platform-espressif32/releases/download/2023.10.03/platform-espressif32.zip
; platform = espressif32 @6.5.0
; platform = https://github.com/tasmota/platform-espressif32/releases/download/2025.01.30/platform-espressif32.zip
; platform = https://github.com/tasmota/platform-espressif32/releases/download/2025.02.30/platform-espressif32.zip
; platform = https://github.com/tasmota/platform-espressif32/releases/download/2025.03.30/platform-espressif32.zip
platform = https://github.com/tasmota/platform-espressif32/releases/download/2025.04.30/platform-espressif32.zip


custom_sdkconfig = file://./sdkconfig.esp32s3
    CONFIG_BOOTLOADER_LOG_LEVEL_VERBOSE=y
    CONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=n
    CONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=y
    CONFIG_ESP_COREDUMP_CHECKSUM_CRC32=y
    CONFIG_ESP_COREDUMP_CHECK_BOOT=y
    CONFIG_ESP_COREDUMP_ENABLE=y
    CONFIG_ESP_COREDUMP_MAX_TASKS_NUM=64
    CONFIG_ESP_COREDUMP_STACK_SIZE=128
    CONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    ARDUINO_USB_CDC_ON_BOOT=1
    USE_USB_CDC_CONSOLE=1
    CONFIG_ARDUINO_USB_CDC_ON_BOOT=y
    CONFIG_USE_USB_CDC_CONSOLE=y
    CONFIG_USB_CDC_ENABLED=y
    CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
    CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
    CONFIG_ESPTOOLPY_FLASHSIZE="8MB"
    CONFIG_FREERTOS_HZ=1000
    CONFIG_ESP32S3_REV_MIN_0=y
    CONFIG_ESPTOOLPY_OCT_FLASH=y
    CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT=y
    CONFIG_SPIRAM_XIP_FROM_PSRAM=y
    CONFIG_SPIRAM_SPEED_80M=y
    CONFIG_SPIRAM_BOOT_INIT=y
    CONFIG_SPIRAM_USE_MALLOC=y
    CONFIG_SPIRAM_MEMTEST=y
    CONFIG_IDF_TARGET="esp32s3"
    CONFIG_IDF_TARGET_ESP32S3=y
    CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
    CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
    CONFIG_PARTITION_TABLE_CUSTOM=y
    CONFIG_COMPILER_OPTIMIZATION_PERF=y
    CONFIG_SPIRAM=y
    CONFIG_SPIRAM_MODE_OCT=y
    CONFIG_SPIRAM_XIP_FROM_PSRAM=y
    CONFIG_SPIRAM_SPEED_80M=y
    CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y
    CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=y
    CONFIG_ESP32S3_DATA_CACHE_64KB=y
    CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
    CONFIG_ESP_SYSTEM_ALLOW_RTC_FAST_MEM_AS_HEAP=n
    CONFIG_FATFS_LFN_HEAP=y
    CONFIG_FREERTOS_HZ=1000
    CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=y
    CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=y
    CONFIG_BSP_SD_FORMAT_ON_MOUNT_FAIL=y
    CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
    CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=y
    CONFIG_ESP32S3_DATA_CACHE_64KB=y
    CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
    CONFIG_ESP32S3_SPIRAM_SUPPORT=y
    CONFIG_FREERTOS_UNICORE=n
    CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
    CONFIG_SPIRAM_RODATA=y
    CONFIG_AUTOSTART_ARDUINO=y

    ;CONFIG_ESP32S3_SPIRAM_SUPPORT=y
    ;CONFIG_SPIRAM_CACHE_WORKAROUND=n
    ;CONFIG_SPIRAM_BOOT_INIT=y
    ;CONFIG_SPIRAM_SPEED_80M=y
    ;CONFIG_SPIRAM_SPEED_120M=y
    ;CONFIG_SPIRAM_BANKSWITCH_ENABLE=y
    ;CONFIG_SPIRAM_MEMTEST=1
    ;CONFIG_COMPILER_CXX_EXCEPTIONS=n
    ;;CONFIG_COMPILER_CXX_RTTI=n
    ;CONFIG_COMPILER_STACK_CHECK_MODE_STRONG=y
    ;CONFIG_SPIRAM_SIZE=-1
    ;CONFIG_SPIRAM_TYPE_AUTO=1
    ;CONFIG_SPIRAM_USE_MALLOC=1
    ;CONFIG_BOOTLOADER_LOG_LEVEL_VERBOSE=y
    ;CONFIG_ESP_CONSOLE_USB_CDC=y
    ; CONFIG_TINYUSB_ENABLED=y
    ;CONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    ;CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
    ;CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=4096
    ;CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=0
    ;CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
    ;CONFIG_SPIRAM_RODATA=y
    ;CONFIG_ESP32S3_DATA_CACHE_64KB=y
    ;CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
    ;CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
    ;CONFIG_SPIRAM_RODATA=y
