;***************************************************;
;         WT32 SC01 Plus with TFT 3.5"              ;
;               - Custom esp32-s3 board             ;
;               - st7796 TFT                        ;
;               - ft6336 touch controller           ;
;***************************************************;

[s3-c1-devkit-hub]
extends = arduino_esp32s3_v2
; board = esp32s3_qio_qspi
; board_build.arduino.memory_type = qio_qspi
board = esp32s3_qio_opi
board_build.arduino.memory_type = qio_opi

# board_build.partitions = default_8MB.csv
board_build.partitions = partitions_8MB.csv

build_flags =
    ${arduino_esp32s3_v2.build_flags}
    ${esp32s3.ps_ram}
    -mno-text-section-literals
    -mlongcalls 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DESP32_PARALLEL
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1    
    -D MACH_UART_PIN_TX=17
    -D MACH_UART_PIN_RX=18
    -D ESP32_HW=1
    -D ESP_NOW_HUB=1

lib_deps =
    ${arduino_esp32s3_v2.lib_deps}

lib_ignore =
  paho
  AXP192
  ArduinoLog
  lv_lib_qrcode
  ETHSPI
  freetype
  LVGL
  https://github.com/lvgl/lvgl
  lvgl

build_src_filter =
  +<*.c>
  +<data/img/*.c>
  +<machine/*.c>
  -<data/font/*.c>
  -<ui/*.c>
  -<data/img/*.c>
  -<main.cpp>
  +<driver/arduino_serial_wrapper.cpp>
  +<driver/mcu_esp32.cpp>
  +<machine/rrf_machine_sim_stream.cpp>
  +<hub_main.cpp>
  +<driver/remote_comms_wrapper.c>
  +<tasks/*.c>

board_upload.maximum_ram_size=2397152

[env:s3-c1-devkit-hub_8MB]
extends = s3-c1-devkit-hub, flash_8mb

[env:s3-c1-devkit-hub_16MB]
extends = s3-c1-devkit-hub, flash_16mb
