/* AUTO-GENERATED by the 'c_code' backend */

#include "lvgl.h"
#include "lvgl_ui.h" // For obj_registry_add, data_binding, etc.
#include <stdlib.h> // For malloc

#include "ui/assets.h"

void create_ui(lv_obj_t* parent) {
    // --- Static Arrays for LVGL properties ---
    static const int32_t s_static_array_11[] = { 80, 80, 80, 536870911 };
    static const int32_t s_static_array_10[] = { 80, 80, 80, 536870911 };
    static const int32_t s_static_array_9[] = { 80, 80, 80, 536870911 };
    static const int32_t s_static_array_8[] = { 80, 80, 80, 536870911 };
    static const int32_t s_static_array_7[] = { 536870810, 536870911 };
    static const int32_t s_static_array_6[] = { 536870810, 536870812, 536870911 };
    static const int32_t s_static_array_5[] = { 536870810, 536870911 };
    static const int32_t s_static_array_4[] = { 22, 50, 12, 50, 536870911 };
    static const int32_t s_static_array_3[] = { 536870810, 536870911 };
    static const int32_t s_static_array_2[] = { 536870810, 536870812, 536870911 };
    static const int32_t s_static_array_1[] = { 536870810, 536870911 };
    static const int32_t s_static_array_0[] = { 536870810, 536870812, 536870911 };

    // font_kode_40: font_kode_40_0 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_40_0 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 40);
    #else
    extern const lv_font_t font_kode_40;
    lv_font_t* font_kode_40_0 = &font_kode_40;
    #endif

    // font_kode_34: font_kode_34_1 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_34_1 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 34);
    #else
    extern const lv_font_t font_kode_34;
    lv_font_t* font_kode_34_1 = &font_kode_34;
    #endif

    // font_kode_30: font_kode_30_2 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_30_2 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 30);
    #else
    extern const lv_font_t font_kode_30;
    lv_font_t* font_kode_30_2 = &font_kode_30;
    #endif

    // font_kode_24: font_kode_24_3 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_24_3 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 24);
    #else
    extern const lv_font_t font_kode_24;
    lv_font_t* font_kode_24_3 = &font_kode_24;
    #endif

    // font_kode_20: font_kode_20_4 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_20_4 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 20);
    #else
    extern const lv_font_t font_kode_20;
    lv_font_t* font_kode_20_4 = &font_kode_20;
    #endif

    // font_kode_14: font_kode_14_5 (font)
    #ifdef LOAD_FONTS_TTF
    lv_font_t* font_kode_14_5 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 14);
    #else
    extern const lv_font_t font_kode_14;
    lv_font_t* font_kode_14_5 = &font_kode_14;
    #endif

    // debug: debug_6 (style)
    lv_style_t* debug_6 = malloc(sizeof(lv_style_t));

    lv_style_init(debug_6);
    obj_registry_add("debug", debug_6);
    lv_style_set_outline_width(debug_6, 1);
    lv_style_set_outline_color(debug_6, lv_color_hex(0xFFEEFF));
    lv_style_set_outline_opa(debug_6, 150);
    lv_style_set_border_width(debug_6, 1);
    lv_style_set_border_color(debug_6, lv_color_hex(0xFFEEFF));
    lv_style_set_border_opa(debug_6, 150);
    lv_style_set_radius(debug_6, 0);

    // container: container_7 (style)
    lv_style_t* container_7 = malloc(sizeof(lv_style_t));

    lv_style_init(container_7);
    obj_registry_add("container", container_7);
    lv_style_set_pad_all(container_7, 0);
    lv_style_set_margin_all(container_7, 0);
    lv_style_set_border_width(container_7, 0);
    lv_style_set_pad_row(container_7, 3);
    lv_style_set_pad_column(container_7, 5);
    lv_style_set_bg_color(container_7, lv_color_hex(0x222222));
    lv_style_set_text_color(container_7, lv_color_hex(0xEBEBCB));
    lv_style_set_radius(container_7, 0);

    // container_transp: container_transp_8 (style)
    lv_style_t* container_transp_8 = malloc(sizeof(lv_style_t));

    lv_style_init(container_transp_8);
    obj_registry_add("container_transp", container_transp_8);
    lv_style_set_pad_all(container_transp_8, 0);
    lv_style_set_margin_all(container_transp_8, 0);
    lv_style_set_border_width(container_transp_8, 0);
    lv_style_set_pad_row(container_transp_8, 3);
    lv_style_set_pad_column(container_transp_8, 5);
    lv_style_set_bg_color(container_transp_8, lv_color_hex(0x222222));
    lv_style_set_text_color(container_transp_8, lv_color_hex(0xEBEBCB));
    lv_style_set_radius(container_transp_8, 0);
    lv_style_set_bg_opa(container_transp_8, 0);

    // bar_indicator: bar_indicator_9 (style)
    lv_style_t* bar_indicator_9 = malloc(sizeof(lv_style_t));

    lv_style_init(bar_indicator_9);
    obj_registry_add("bar_indicator", bar_indicator_9);
    lv_style_set_radius(bar_indicator_9, 4);

    // bg_gradient: bg_gradient_10 (style)
    lv_style_t* bg_gradient_10 = malloc(sizeof(lv_style_t));

    lv_style_init(bg_gradient_10);
    obj_registry_add("bg_gradient", bg_gradient_10);
    lv_style_set_bg_opa(bg_gradient_10, 255);
    lv_style_set_bg_color(bg_gradient_10, lv_color_hex(0x222222));
    lv_style_set_bg_grad_color(bg_gradient_10, lv_color_hex(0x444444));
    lv_style_set_bg_grad_dir(bg_gradient_10, LV_GRAD_DIR_HOR);

    // flex_x: flex_x_11 (style)
    lv_style_t* flex_x_11 = malloc(sizeof(lv_style_t));

    lv_style_init(flex_x_11);
    obj_registry_add("flex_x", flex_x_11);
    lv_style_set_layout(flex_x_11, LV_LAYOUT_FLEX);
    lv_style_set_flex_flow(flex_x_11, LV_FLEX_FLOW_ROW);

    // flex_y: flex_y_12 (style)
    lv_style_t* flex_y_12 = malloc(sizeof(lv_style_t));

    lv_style_init(flex_y_12);
    obj_registry_add("flex_y", flex_y_12);
    lv_style_set_layout(flex_y_12, LV_LAYOUT_FLEX);
    lv_style_set_flex_flow(flex_y_12, LV_FLEX_FLOW_COLUMN);

    // indicator_green: indicator_green_13 (style)
    lv_style_t* indicator_green_13 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_green_13);
    obj_registry_add("indicator_green", indicator_green_13);
    lv_style_set_text_color(indicator_green_13, lv_color_hex(0x44EE44));

    // indicator_yellow: indicator_yellow_14 (style)
    lv_style_t* indicator_yellow_14 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_yellow_14);
    obj_registry_add("indicator_yellow", indicator_yellow_14);
    lv_style_set_text_color(indicator_yellow_14, lv_color_hex(0xFFFF55));

    // text_actionable: text_actionable_15 (style)
    lv_style_t* text_actionable_15 = malloc(sizeof(lv_style_t));

    lv_style_init(text_actionable_15);
    obj_registry_add("text_actionable", text_actionable_15);
    lv_style_set_text_color(text_actionable_15, lv_color_hex(0xFFFF55));
    lv_style_set_text_font(text_actionable_15, font_kode_14_5);

    // jog_btn: jog_btn_16 (style)
    lv_style_t* jog_btn_16 = malloc(sizeof(lv_style_t));

    lv_style_init(jog_btn_16);
    obj_registry_add("jog_btn", jog_btn_16);
    lv_style_set_pad_all(jog_btn_16, 5);
    lv_style_set_pad_bottom(jog_btn_16, 10);
    lv_style_set_pad_top(jog_btn_16, 10);
    lv_style_set_margin_all(jog_btn_16, 0);
    lv_style_set_radius(jog_btn_16, 2);

    // border_top_btn: border_top_btn_17 (style)
    lv_style_t* border_top_btn_17 = malloc(sizeof(lv_style_t));

    lv_style_init(border_top_btn_17);
    obj_registry_add("border_top_btn", border_top_btn_17);
    lv_style_set_border_width(border_top_btn_17, 1);
    lv_style_set_border_color(border_top_btn_17, lv_color_hex(0xFFFFFF));
    lv_style_set_border_opa(border_top_btn_17, 50);
    lv_style_set_border_side(border_top_btn_17, 3);

    // border_right: border_right_18 (style)
    lv_style_t* border_right_18 = malloc(sizeof(lv_style_t));

    lv_style_init(border_right_18);
    obj_registry_add("border_right", border_right_18);
    lv_style_set_border_width(border_right_18, 1);
    lv_style_set_border_color(border_right_18, lv_color_hex(0xFFFFFF));
    lv_style_set_border_opa(border_right_18, 50);
    lv_style_set_border_side(border_right_18, LV_BORDER_SIDE_RIGHT);

    // indicator_light: indicator_light_19 (style)
    lv_style_t* indicator_light_19 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_19);
    obj_registry_add("indicator_light", indicator_light_19);
    lv_style_set_border_width(indicator_light_19, 6);
    lv_style_set_pad_left(indicator_light_19, 12);
    lv_style_set_margin_left(indicator_light_19, 5);
    lv_style_set_border_opa(indicator_light_19, 200);
    lv_style_set_border_side(indicator_light_19, LV_BORDER_SIDE_LEFT);

    // indicator_light_red: indicator_light_red_20 (style)
    lv_style_t* indicator_light_red_20 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_red_20);
    obj_registry_add("indicator_light_red", indicator_light_red_20);
    lv_style_set_border_color(indicator_light_red_20, lv_color_hex(0xFF5555));

    // indicator_light_green: indicator_light_green_21 (style)
    lv_style_t* indicator_light_green_21 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_green_21);
    obj_registry_add("indicator_light_green", indicator_light_green_21);
    lv_style_set_border_color(indicator_light_green_21, lv_color_hex(0x55FF55));

    // indicator_light_yellow: indicator_light_yellow_22 (style)
    lv_style_t* indicator_light_yellow_22 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_yellow_22);
    obj_registry_add("indicator_light_yellow", indicator_light_yellow_22);
    lv_style_set_border_color(indicator_light_yellow_22, lv_color_hex(0xFFFF55));

    // debug: debug_23 (style)
    lv_style_t* debug_23 = malloc(sizeof(lv_style_t));

    lv_style_init(debug_23);
    obj_registry_add("debug", debug_23);
    lv_style_set_bg_color(debug_23, lv_color_hex(0xF000F0));
    lv_style_set_bg_opa(debug_23, LV_OPA_COVER);

    // btn_clicked: btn_clicked_24 (style)
    lv_style_t* btn_clicked_24 = malloc(sizeof(lv_style_t));

    lv_style_init(btn_clicked_24);
    obj_registry_add("btn_clicked", btn_clicked_24);
    lv_style_set_bg_color(btn_clicked_24, lv_color_hex(0x777777));
    lv_style_set_bg_opa(btn_clicked_24, 60);

    // bg_group: bg_group_25 (style)
    lv_style_t* bg_group_25 = malloc(sizeof(lv_style_t));

    lv_style_init(bg_group_25);
    obj_registry_add("bg_group", bg_group_25);
    lv_style_set_bg_opa(bg_group_25, 40);
    lv_style_set_bg_color(bg_group_25, lv_color_hex(0x111111));

    // tick_color: tick_color_26 (style)
    lv_style_t* tick_color_26 = malloc(sizeof(lv_style_t));

    lv_style_init(tick_color_26);
    obj_registry_add("tick_color", tick_color_26);
    lv_style_set_line_color(tick_color_26, lv_color_hex(0x777777));

    // unnamed: obj_27 (obj)
    lv_obj_t* obj_27 = lv_screen_active();

    lv_obj_add_style(obj_27, container_7, 0);

    // unnamed: tileview_28 (tileview)
    lv_obj_t* tileview_28 = lv_tileview_create(parent);

    lv_obj_add_style(tileview_28, container_7, 0);
    lv_obj_set_style_size(tileview_28, lv_pct(100), lv_pct(100), 0);
    lv_obj_set_style_pad_row(tileview_28, 0, 0);
    lv_obj_set_style_pad_column(tileview_28, 0, 0);
    lv_obj_set_scrollbar_mode(tileview_28, LV_SCROLLBAR_MODE_ACTIVE);
    // unnamed: obj_29 (obj)
    lv_obj_t* obj_29 = lv_tileview_add_tile(tileview_28, 0, 0, LV_DIR_RIGHT);

    lv_obj_add_style(obj_29, container_7, 0);
    // main: main_30 (obj)
    lv_obj_t* main_30 = lv_obj_create(obj_29);

    obj_registry_add("main", main_30);
    lv_obj_set_style_layout(main_30, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(main_30, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_flex_align(main_30, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_style(main_30, container_7, 0);
    lv_obj_set_style_size(main_30, lv_pct(100), lv_pct(100), 0);
    lv_obj_remove_flag(main_30, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_border_width(main_30, 0, 0);
    lv_obj_set_style_pad_all(main_30, 0, 0);
    lv_obj_set_style_margin_all(main_30, 0, 0);
    lv_obj_set_style_outline_width(main_30, 0, 0);
    // unnamed: obj_31 (obj)
    lv_obj_t* obj_31 = lv_obj_create(main_30);

    lv_obj_set_style_layout(obj_31, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_31, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_31, container_7, 0);
    lv_obj_set_style_height(obj_31, lv_pct(100), 0);
    lv_obj_set_style_flex_grow(obj_31, 4, 0);
    lv_obj_set_style_border_side(obj_31, LV_BORDER_SIDE_RIGHT, 0);
    lv_obj_set_style_border_width(obj_31, 1, 0);
    lv_obj_set_style_radius(obj_31, 0, 0);
    lv_obj_set_style_border_color(obj_31, lv_color_hex(0x333333), 0);
    lv_obj_set_style_border_opa(obj_31, 255, 0);
    // unnamed: obj_32 (obj)
    lv_obj_t* obj_32 = lv_obj_create(obj_31);

    lv_obj_set_style_size(obj_32, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_32, container_7, 0);
    lv_obj_add_style(obj_32, flex_y_12, 0);
    lv_obj_add_style(obj_32, bg_gradient_10, 0);
    lv_obj_set_style_bg_opa(obj_32, 255, 0);
    lv_obj_set_style_pad_column(obj_32, 0, 0);
    lv_obj_set_style_pad_row(obj_32, 0, 0);
    lv_obj_remove_flag(obj_32, LV_OBJ_FLAG_SCROLLABLE);
    // $name: __name_33 (obj)
    lv_obj_t* __name_33 = lv_obj_create(obj_32);

    obj_registry_add("$name", __name_33);
    lv_obj_add_style(__name_33, flex_x_11, 0);
    lv_obj_add_style(__name_33, container_transp_8, 0);
    lv_obj_add_style(__name_33, bg_group_25, 0);
    lv_obj_set_style_size(__name_33, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_33, 10, 0);
    lv_obj_set_style_pad_bottom(__name_33, 18, 0);
    lv_obj_set_style_border_color(__name_33, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_33, 40, 0);
    lv_obj_set_style_margin_all(__name_33, 2, 0);
    // unnamed: button_34 (button)
    lv_obj_t* button_34 = lv_button_create(__name_33);

    lv_obj_set_style_text_font(button_34, font_kode_40_0, 0);
    lv_obj_set_style_width(button_34, 35, 0);
    lv_obj_add_style(button_34, indicator_light_19, 0);
    lv_obj_add_style(button_34, btn_clicked_24, LV_STATE_PRESSED);
    data_binding_add_observer("x_is_homed", button_34, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_action(button_34, "home_machine", 0, NULL, 0, NULL);
    lv_obj_set_style_radius(button_34, 0, 0);
    lv_obj_set_style_bg_opa(button_34, 0, 0);
    lv_obj_set_style_shadow_opa(button_34, 0, 0);
    lv_obj_set_style_pad_right(button_34, 0, 0);
    lv_obj_set_style_pad_bottom(button_34, 0, 0);
    lv_obj_set_style_pad_top(button_34, 0, 0);
    // unnamed: label_35 (label)
    lv_obj_t* label_35 = lv_label_create(button_34);

    lv_label_set_text(label_35, "X");
    lv_obj_center(label_35);


    // unnamed: obj_36 (obj)
    lv_obj_t* obj_36 = lv_obj_create(__name_33);

    lv_obj_add_style(obj_36, flex_y_12, 0);
    lv_obj_add_style(obj_36, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_36, 1, 0);
    lv_obj_set_style_height(obj_36, 1073741823, 0);
    // unnamed: obj_37 (obj)
    lv_obj_t* obj_37 = lv_obj_create(obj_36);

    lv_obj_add_style(obj_37, flex_x_11, 0);
    lv_obj_add_style(obj_37, container_transp_8, 0);
    lv_obj_set_style_size(obj_37, lv_pct(100), 1073741823, 0);
    // unnamed: label_38 (label)
    lv_obj_t* label_38 = lv_label_create(obj_37);

    lv_obj_set_style_text_font(label_38, font_kode_34_1, 0);
    lv_label_set_text(label_38, "000.00 G54");
    lv_obj_set_style_flex_grow(label_38, 1, 0);
    lv_obj_add_style(label_38, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_38, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_x", label_38, 0, "%4.2f", 0, NULL);


    // unnamed: obj_39 (obj)
    lv_obj_t* obj_39 = lv_obj_create(obj_36);

    lv_obj_add_style(obj_39, flex_x_11, 0);
    lv_obj_add_style(obj_39, container_transp_8, 0);
    lv_obj_set_style_size(obj_39, lv_pct(100), 1073741823, 0);
    // unnamed: label_40 (label)
    lv_obj_t* label_40 = lv_label_create(obj_39);

    lv_obj_set_style_text_font(label_40, font_kode_14_5, 0);
    lv_label_set_text(label_40, "000.00");
    lv_obj_set_style_flex_grow(label_40, 1, 0);
    lv_obj_set_style_text_align(label_40, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_40, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_x", label_40, 0, "%4.2f", 0, NULL);

    // unnamed: label_41 (label)
    lv_obj_t* label_41 = lv_label_create(obj_39);

    lv_label_set_text(label_41, "\xef\x84\xa4");
    lv_obj_set_style_width(label_41, 14, 0);

    // unnamed: label_42 (label)
    lv_obj_t* label_42 = lv_label_create(obj_39);

    lv_obj_set_style_text_font(label_42, font_kode_14_5, 0);
    lv_label_set_text(label_42, "000.00   ");
    lv_obj_set_style_text_align(label_42, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_42, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_42, 1, 0);
    data_binding_add_observer("delta_pos_x", label_42, 0, "%4.2f", 0, NULL);

    // unnamed: label_43 (label)
    lv_obj_t* label_43 = lv_label_create(obj_39);

    lv_label_set_text(label_43, "\xef\x81\x91");
    lv_obj_set_style_width(label_43, 14, 0);




    // $name: __name_44 (obj)
    lv_obj_t* __name_44 = lv_obj_create(obj_32);

    obj_registry_add("$name", __name_44);
    lv_obj_add_style(__name_44, flex_x_11, 0);
    lv_obj_add_style(__name_44, container_transp_8, 0);
    lv_obj_add_style(__name_44, bg_group_25, 0);
    lv_obj_set_style_size(__name_44, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_44, 10, 0);
    lv_obj_set_style_pad_bottom(__name_44, 18, 0);
    lv_obj_set_style_border_color(__name_44, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_44, 40, 0);
    lv_obj_set_style_margin_all(__name_44, 2, 0);
    // unnamed: button_45 (button)
    lv_obj_t* button_45 = lv_button_create(__name_44);

    lv_obj_set_style_text_font(button_45, font_kode_40_0, 0);
    lv_obj_set_style_width(button_45, 35, 0);
    lv_obj_add_style(button_45, indicator_light_19, 0);
    lv_obj_add_style(button_45, btn_clicked_24, LV_STATE_PRESSED);
    data_binding_add_observer("y_is_homed", button_45, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_action(button_45, "home_machine", 0, NULL, 0, NULL);
    lv_obj_set_style_radius(button_45, 0, 0);
    lv_obj_set_style_bg_opa(button_45, 0, 0);
    lv_obj_set_style_shadow_opa(button_45, 0, 0);
    lv_obj_set_style_pad_right(button_45, 0, 0);
    lv_obj_set_style_pad_bottom(button_45, 0, 0);
    lv_obj_set_style_pad_top(button_45, 0, 0);
    // unnamed: label_46 (label)
    lv_obj_t* label_46 = lv_label_create(button_45);

    lv_label_set_text(label_46, "Y");
    lv_obj_center(label_46);


    // unnamed: obj_47 (obj)
    lv_obj_t* obj_47 = lv_obj_create(__name_44);

    lv_obj_add_style(obj_47, flex_y_12, 0);
    lv_obj_add_style(obj_47, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_47, 1, 0);
    lv_obj_set_style_height(obj_47, 1073741823, 0);
    // unnamed: obj_48 (obj)
    lv_obj_t* obj_48 = lv_obj_create(obj_47);

    lv_obj_add_style(obj_48, flex_x_11, 0);
    lv_obj_add_style(obj_48, container_transp_8, 0);
    lv_obj_set_style_size(obj_48, lv_pct(100), 1073741823, 0);
    // unnamed: label_49 (label)
    lv_obj_t* label_49 = lv_label_create(obj_48);

    lv_obj_set_style_text_font(label_49, font_kode_34_1, 0);
    lv_label_set_text(label_49, "000.00");
    lv_obj_set_style_flex_grow(label_49, 1, 0);
    lv_obj_add_style(label_49, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_49, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_y", label_49, 0, "%4.2f", 0, NULL);


    // unnamed: obj_50 (obj)
    lv_obj_t* obj_50 = lv_obj_create(obj_47);

    lv_obj_add_style(obj_50, flex_x_11, 0);
    lv_obj_add_style(obj_50, container_transp_8, 0);
    lv_obj_set_style_size(obj_50, lv_pct(100), 1073741823, 0);
    // unnamed: label_51 (label)
    lv_obj_t* label_51 = lv_label_create(obj_50);

    lv_obj_set_style_text_font(label_51, font_kode_14_5, 0);
    lv_label_set_text(label_51, "000.00");
    lv_obj_set_style_flex_grow(label_51, 1, 0);
    lv_obj_set_style_text_align(label_51, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_51, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_y", label_51, 0, "%4.2f", 0, NULL);

    // unnamed: label_52 (label)
    lv_obj_t* label_52 = lv_label_create(obj_50);

    lv_label_set_text(label_52, "\xef\x84\xa4");
    lv_obj_set_style_width(label_52, 14, 0);

    // unnamed: label_53 (label)
    lv_obj_t* label_53 = lv_label_create(obj_50);

    lv_obj_set_style_text_font(label_53, font_kode_14_5, 0);
    lv_label_set_text(label_53, "000.00   ");
    lv_obj_set_style_text_align(label_53, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_53, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_53, 1, 0);
    data_binding_add_observer("delta_pos_y", label_53, 0, "%4.2f", 0, NULL);

    // unnamed: label_54 (label)
    lv_obj_t* label_54 = lv_label_create(obj_50);

    lv_label_set_text(label_54, "\xef\x81\x91");
    lv_obj_set_style_width(label_54, 14, 0);




    // $name: __name_55 (obj)
    lv_obj_t* __name_55 = lv_obj_create(obj_32);

    obj_registry_add("$name", __name_55);
    lv_obj_add_style(__name_55, flex_x_11, 0);
    lv_obj_add_style(__name_55, container_transp_8, 0);
    lv_obj_add_style(__name_55, bg_group_25, 0);
    lv_obj_set_style_size(__name_55, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_55, 10, 0);
    lv_obj_set_style_pad_bottom(__name_55, 18, 0);
    lv_obj_set_style_border_color(__name_55, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_55, 40, 0);
    lv_obj_set_style_margin_all(__name_55, 2, 0);
    // unnamed: button_56 (button)
    lv_obj_t* button_56 = lv_button_create(__name_55);

    lv_obj_set_style_text_font(button_56, font_kode_40_0, 0);
    lv_obj_set_style_width(button_56, 35, 0);
    lv_obj_add_style(button_56, indicator_light_19, 0);
    lv_obj_add_style(button_56, btn_clicked_24, LV_STATE_PRESSED);
    data_binding_add_observer("z_is_homed", button_56, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_action(button_56, "home_machine", 0, NULL, 0, NULL);
    lv_obj_set_style_radius(button_56, 0, 0);
    lv_obj_set_style_bg_opa(button_56, 0, 0);
    lv_obj_set_style_shadow_opa(button_56, 0, 0);
    lv_obj_set_style_pad_right(button_56, 0, 0);
    lv_obj_set_style_pad_bottom(button_56, 0, 0);
    lv_obj_set_style_pad_top(button_56, 0, 0);
    // unnamed: label_57 (label)
    lv_obj_t* label_57 = lv_label_create(button_56);

    lv_label_set_text(label_57, "Z");
    lv_obj_center(label_57);


    // unnamed: obj_58 (obj)
    lv_obj_t* obj_58 = lv_obj_create(__name_55);

    lv_obj_add_style(obj_58, flex_y_12, 0);
    lv_obj_add_style(obj_58, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_58, 1, 0);
    lv_obj_set_style_height(obj_58, 1073741823, 0);
    // unnamed: obj_59 (obj)
    lv_obj_t* obj_59 = lv_obj_create(obj_58);

    lv_obj_add_style(obj_59, flex_x_11, 0);
    lv_obj_add_style(obj_59, container_transp_8, 0);
    lv_obj_set_style_size(obj_59, lv_pct(100), 1073741823, 0);
    // unnamed: label_60 (label)
    lv_obj_t* label_60 = lv_label_create(obj_59);

    lv_obj_set_style_text_font(label_60, font_kode_34_1, 0);
    lv_label_set_text(label_60, "000.00");
    lv_obj_set_style_flex_grow(label_60, 1, 0);
    lv_obj_add_style(label_60, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_60, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_z", label_60, 0, "%4.2f", 0, NULL);


    // unnamed: obj_61 (obj)
    lv_obj_t* obj_61 = lv_obj_create(obj_58);

    lv_obj_add_style(obj_61, flex_x_11, 0);
    lv_obj_add_style(obj_61, container_transp_8, 0);
    lv_obj_set_style_size(obj_61, lv_pct(100), 1073741823, 0);
    // unnamed: label_62 (label)
    lv_obj_t* label_62 = lv_label_create(obj_61);

    lv_obj_set_style_text_font(label_62, font_kode_14_5, 0);
    lv_label_set_text(label_62, "000.00");
    lv_obj_set_style_flex_grow(label_62, 1, 0);
    lv_obj_set_style_text_align(label_62, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_62, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_z", label_62, 0, "%4.2f", 0, NULL);

    // unnamed: label_63 (label)
    lv_obj_t* label_63 = lv_label_create(obj_61);

    lv_label_set_text(label_63, "\xef\x84\xa4");
    lv_obj_set_style_width(label_63, 14, 0);

    // unnamed: label_64 (label)
    lv_obj_t* label_64 = lv_label_create(obj_61);

    lv_obj_set_style_text_font(label_64, font_kode_14_5, 0);
    lv_label_set_text(label_64, "000.00   ");
    lv_obj_set_style_text_align(label_64, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_64, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_64, 1, 0);
    data_binding_add_observer("delta_pos_z", label_64, 0, "%4.2f", 0, NULL);

    // unnamed: label_65 (label)
    lv_obj_t* label_65 = lv_label_create(obj_61);

    lv_label_set_text(label_65, "\xef\x81\x91");
    lv_obj_set_style_width(label_65, 14, 0);




    // unnamed: obj_66 (obj)
    lv_obj_t* obj_66 = lv_obj_create(obj_32);

    lv_obj_set_style_layout(obj_66, LV_LAYOUT_FLEX, 0);
    lv_obj_set_flex_align(obj_66, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_style(obj_66, container_transp_8, 0);
    lv_obj_set_style_size(obj_66, 1073741823, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_66, 5, 0);
    // unnamed: button_67 (button)
    lv_obj_t* button_67 = lv_button_create(obj_66);

    data_binding_add_observer("program_running", button_67, 2, &(bool){NULL}, 0, NULL);
    // unnamed: label_68 (label)
    lv_obj_t* label_68 = lv_label_create(button_67);

    lv_label_set_text(label_68, "\xef\x81\x8b");
    lv_obj_set_style_width(label_68, 1073741823, 0);
    data_binding_add_action(label_68, "program_run", 0, NULL, 0, NULL);


    // unnamed: button_69 (button)
    lv_obj_t* button_69 = lv_button_create(obj_66);

    data_binding_add_observer("program_running", button_69, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = true } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = false } } }, 2, NULL);
    // unnamed: label_70 (label)
    lv_obj_t* label_70 = lv_label_create(button_69);

    lv_label_set_text(label_70, "\xef\x81\x8d");
    lv_obj_set_style_width(label_70, 1073741823, 0);
    data_binding_add_action(label_70, "program_stop", 0, NULL, 0, NULL);


    // unnamed: label_71 (label)
    lv_obj_t* label_71 = lv_label_create(obj_66);

    data_binding_add_observer("machine_mode", label_71, 0, "MODE: %s", 0, NULL);

    // unnamed: label_72 (label)
    lv_obj_t* label_72 = lv_label_create(obj_66);

    lv_obj_add_style(label_72, indicator_yellow_14, 0);
    data_binding_add_observer("wcs_name", label_72, 0, "- %s", 0, NULL);
    data_binding_add_action(label_72, "cycle_wcs", 0, NULL, 0, NULL);




    // unnamed: obj_73 (obj)
    lv_obj_t* obj_73 = lv_obj_create(main_30);

    lv_obj_set_style_layout(obj_73, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_73, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_73, container_7, 0);
    lv_obj_add_style(obj_73, bg_gradient_10, 0);
    lv_obj_set_style_height(obj_73, lv_pct(100), 0);
    lv_obj_set_style_flex_grow(obj_73, 4, 0);
    lv_obj_set_style_pad_top(obj_73, 2, 0);
    lv_obj_set_style_pad_right(obj_73, 2, 0);
    lv_obj_set_style_margin_left(obj_73, 2, 0);
    lv_obj_set_style_margin_right(obj_73, 2, 0);
    // unnamed: obj_74 (obj)
    lv_obj_t* obj_74 = lv_obj_create(obj_73);

    lv_obj_set_style_size(obj_74, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_74, container_transp_8, 0);
    lv_obj_add_style(obj_74, bg_group_25, 0);
    lv_obj_set_style_layout(obj_74, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_74, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_74, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_74, 0, 0);
    lv_obj_set_style_pad_bottom(obj_74, 4, 0);
    lv_obj_set_style_pad_top(obj_74, 4, 0);
    // unnamed: obj_75 (obj)
    lv_obj_t* obj_75 = lv_obj_create(obj_74);

    lv_obj_set_style_layout(obj_75, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_75, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_75, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_75, lv_pct(100), 0);
    lv_obj_set_style_height(obj_75, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_75, 1, 0);
    // unnamed: obj_76 (obj)
    lv_obj_t* obj_76 = lv_obj_create(obj_75);

    lv_obj_set_style_layout(obj_76, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_76, s_static_array_0, s_static_array_1);
    lv_obj_add_style(obj_76, container_transp_8, 0);
    lv_obj_set_style_width(obj_76, lv_pct(100), 0);
    lv_obj_set_style_height(obj_76, 1073741823, 0);
    // unnamed: obj_77 (obj)
    lv_obj_t* obj_77 = lv_obj_create(obj_76);

    lv_obj_set_style_layout(obj_77, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_77, 100, 1073741823, 0);
    lv_obj_add_style(obj_77, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_77, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_77, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_77, 0, 0);
    lv_obj_set_style_pad_bottom(obj_77, -8, 0);
    // unnamed: label_78 (label)
    lv_obj_t* label_78 = lv_label_create(obj_77);

    lv_label_set_text(label_78, "F");
    lv_obj_set_style_text_font(label_78, font_kode_40_0, 0);
    lv_obj_set_style_height(label_78, 1073741823, 0);
    lv_obj_set_style_pad_left(label_78, 5, 0);

    // unnamed: label_79 (label)
    lv_obj_t* label_79 = lv_label_create(obj_77);

    lv_label_set_text(label_79, "FEED");
    lv_obj_set_style_pad_left(label_79, 0, 0);
    lv_obj_set_style_height(label_79, 1073741823, 0);
    lv_obj_set_style_text_font(label_79, font_kode_14_5, 0);
    lv_obj_add_style(label_79, border_top_btn_17, 0);


    // unnamed: label_80 (label)
    lv_obj_t* label_80 = lv_label_create(obj_76);

    lv_obj_set_grid_cell(label_80, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_80, font_kode_30_2, 0);
    lv_obj_set_style_height(label_80, 1073741823, 0);
    lv_label_set_text(label_80, "1000");
    lv_obj_set_style_pad_right(label_80, 5, 0);
    data_binding_add_observer("feed", label_80, 0, "%.0f", 0, NULL);


    // unnamed: obj_81 (obj)
    lv_obj_t* obj_81 = lv_obj_create(obj_75);

    lv_obj_set_style_layout(obj_81, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_81, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_81, container_transp_8, 0);
    lv_obj_set_style_width(obj_81, lv_pct(100), 0);
    lv_obj_set_style_height(obj_81, 1073741823, 0);
    // unnamed: bar_82 (bar)
    lv_obj_t* bar_82 = lv_bar_create(obj_81);

    lv_obj_set_style_width(bar_82, lv_pct(100), 0);
    lv_obj_set_style_height(bar_82, 15, 0);
    lv_obj_set_style_margin_left(bar_82, 15, 0);
    lv_obj_set_style_margin_right(bar_82, 15, 0);
    lv_obj_add_style(bar_82, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_82, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_82, 65, 0);
    lv_bar_set_range(bar_82, 0, 5000);
    lv_obj_set_style_bg_color(bar_82, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_82, 255, 0);
    data_binding_add_observer("feed", bar_82, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_83 (scale)
    lv_obj_t* scale_83 = lv_scale_create(obj_81);

    lv_obj_set_style_width(scale_83, lv_pct(100), 0);
    lv_obj_set_style_height(scale_83, 18, 0);
    lv_obj_set_style_margin_left(scale_83, 15, 0);
    lv_obj_set_style_margin_right(scale_83, 15, 0);
    lv_obj_set_style_margin_bottom(scale_83, 2, 0);
    lv_obj_add_style(scale_83, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_83, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_83, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_84 (obj)
    lv_obj_t* obj_84 = lv_obj_create(obj_74);

    lv_obj_set_style_layout(obj_84, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_84, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_84, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_size(obj_84, 1073741823, 1073741823, 0);
    lv_obj_set_style_min_width(obj_84, 50, 0);
    lv_obj_set_style_pad_right(obj_84, 0, 0);
    lv_obj_set_flex_align(obj_84, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_84, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_pad_top(obj_84, 18, 0);
    data_binding_add_action(obj_84, "set_feed_override", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);
    // unnamed: label_85 (label)
    lv_obj_t* label_85 = lv_label_create(obj_84);

    lv_label_set_text(label_85, "MM/MIN");
    lv_obj_set_style_text_font(label_85, font_kode_14_5, 0);
    lv_obj_add_style(label_85, border_top_btn_17, 0);

    // unnamed: label_86 (label)
    lv_obj_t* label_86 = lv_label_create(obj_84);

    lv_label_set_text(label_86, "F Ovr");

    // unnamed: label_87 (label)
    lv_obj_t* label_87 = lv_label_create(obj_84);

    lv_label_set_text(label_87, "65%%");
    lv_obj_set_style_text_font(label_87, font_kode_14_5, 0);
    lv_obj_add_style(label_87, indicator_yellow_14, 0);
    data_binding_add_observer("feed_override_pct", label_87, 0, "%g%%", 0, NULL);



    // unnamed: obj_88 (obj)
    lv_obj_t* obj_88 = lv_obj_create(obj_73);

    lv_obj_set_style_size(obj_88, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_88, container_transp_8, 0);
    lv_obj_add_style(obj_88, bg_group_25, 0);
    lv_obj_set_style_layout(obj_88, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_88, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_88, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_88, 0, 0);
    lv_obj_set_style_pad_bottom(obj_88, 4, 0);
    lv_obj_set_style_pad_top(obj_88, 4, 0);
    // unnamed: obj_89 (obj)
    lv_obj_t* obj_89 = lv_obj_create(obj_88);

    lv_obj_set_style_layout(obj_89, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_89, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_89, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_89, lv_pct(100), 0);
    lv_obj_set_style_height(obj_89, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_89, 1, 0);
    // unnamed: obj_90 (obj)
    lv_obj_t* obj_90 = lv_obj_create(obj_89);

    lv_obj_set_style_layout(obj_90, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_90, s_static_array_2, s_static_array_3);
    lv_obj_add_style(obj_90, container_transp_8, 0);
    lv_obj_set_style_width(obj_90, lv_pct(100), 0);
    lv_obj_set_style_height(obj_90, 1073741823, 0);
    // unnamed: obj_91 (obj)
    lv_obj_t* obj_91 = lv_obj_create(obj_90);

    lv_obj_set_style_layout(obj_91, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_91, 100, 1073741823, 0);
    lv_obj_add_style(obj_91, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_91, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_91, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_91, 0, 0);
    lv_obj_set_style_pad_bottom(obj_91, -8, 0);
    // unnamed: label_92 (label)
    lv_obj_t* label_92 = lv_label_create(obj_91);

    lv_label_set_text(label_92, "S");
    lv_obj_set_style_text_font(label_92, font_kode_40_0, 0);
    lv_obj_set_style_height(label_92, 1073741823, 0);
    lv_obj_set_style_pad_left(label_92, 5, 0);

    // unnamed: label_93 (label)
    lv_obj_t* label_93 = lv_label_create(obj_91);

    lv_label_set_text(label_93, "SPEED");
    lv_obj_set_style_pad_left(label_93, 0, 0);
    lv_obj_set_style_height(label_93, 1073741823, 0);
    lv_obj_set_style_text_font(label_93, font_kode_14_5, 0);
    lv_obj_add_style(label_93, border_top_btn_17, 0);


    // unnamed: label_94 (label)
    lv_obj_t* label_94 = lv_label_create(obj_90);

    lv_obj_set_grid_cell(label_94, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_94, font_kode_30_2, 0);
    lv_obj_set_style_height(label_94, 1073741823, 0);
    lv_label_set_text(label_94, "1000");
    lv_obj_set_style_pad_right(label_94, 5, 0);
    data_binding_add_observer("spindle_rpm", label_94, 0, "%.0f", 0, NULL);


    // unnamed: obj_95 (obj)
    lv_obj_t* obj_95 = lv_obj_create(obj_89);

    lv_obj_set_style_layout(obj_95, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_95, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_95, container_transp_8, 0);
    lv_obj_set_style_width(obj_95, lv_pct(100), 0);
    lv_obj_set_style_height(obj_95, 1073741823, 0);
    // unnamed: bar_96 (bar)
    lv_obj_t* bar_96 = lv_bar_create(obj_95);

    lv_obj_set_style_width(bar_96, lv_pct(100), 0);
    lv_obj_set_style_height(bar_96, 15, 0);
    lv_obj_set_style_margin_left(bar_96, 15, 0);
    lv_obj_set_style_margin_right(bar_96, 15, 0);
    lv_obj_add_style(bar_96, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_96, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_96, 65, 0);
    lv_bar_set_range(bar_96, 0, 24000);
    lv_obj_set_style_bg_color(bar_96, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_96, 255, 0);
    data_binding_add_observer("spindle_rpm", bar_96, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_97 (scale)
    lv_obj_t* scale_97 = lv_scale_create(obj_95);

    lv_obj_set_style_width(scale_97, lv_pct(100), 0);
    lv_obj_set_style_height(scale_97, 18, 0);
    lv_obj_set_style_margin_left(scale_97, 15, 0);
    lv_obj_set_style_margin_right(scale_97, 15, 0);
    lv_obj_set_style_margin_bottom(scale_97, 2, 0);
    lv_obj_add_style(scale_97, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_97, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_97, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_98 (obj)
    lv_obj_t* obj_98 = lv_obj_create(obj_88);

    lv_obj_set_style_layout(obj_98, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_98, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_98, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_size(obj_98, 1073741823, 1073741823, 0);
    lv_obj_set_style_min_width(obj_98, 50, 0);
    lv_obj_set_style_pad_right(obj_98, 0, 0);
    lv_obj_set_flex_align(obj_98, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_98, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_pad_top(obj_98, 18, 0);
    data_binding_add_action(obj_98, "set_speed_override", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);
    // unnamed: label_99 (label)
    lv_obj_t* label_99 = lv_label_create(obj_98);

    lv_label_set_text(label_99, "/MIN");
    lv_obj_set_style_text_font(label_99, font_kode_14_5, 0);
    lv_obj_add_style(label_99, border_top_btn_17, 0);

    // unnamed: label_100 (label)
    lv_obj_t* label_100 = lv_label_create(obj_98);

    lv_label_set_text(label_100, "S Ovr");

    // unnamed: label_101 (label)
    lv_obj_t* label_101 = lv_label_create(obj_98);

    lv_label_set_text(label_101, "65%%");
    lv_obj_set_style_text_font(label_101, font_kode_14_5, 0);
    lv_obj_add_style(label_101, indicator_yellow_14, 0);
    data_binding_add_observer("speed_override_pct", label_101, 0, "%g%%", 0, NULL);



    // unnamed: obj_102 (obj)
    lv_obj_t* obj_102 = lv_obj_create(obj_73);

    lv_obj_set_style_size(obj_102, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_102, container_transp_8, 0);
    lv_obj_add_style(obj_102, bg_group_25, 0);
    lv_obj_set_style_layout(obj_102, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_102, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_102, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_102, 0, 0);
    lv_obj_set_style_pad_bottom(obj_102, 18, 0);
    lv_obj_set_style_pad_top(obj_102, 18, 0);
    // unnamed: obj_103 (obj)
    lv_obj_t* obj_103 = lv_obj_create(obj_102);

    lv_obj_set_style_layout(obj_103, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_103, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_103, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_103, lv_pct(100), 0);
    lv_obj_set_style_height(obj_103, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_103, 1, 0);
    // unnamed: label_104 (label)
    lv_obj_t* label_104 = lv_label_create(obj_103);

    lv_label_set_text(label_104, "JOG");
    lv_obj_set_style_height(label_104, 1073741823, 0);
    lv_obj_set_style_width(label_104, lv_pct(100), 0);
    lv_obj_set_style_text_font(label_104, font_kode_20_4, 0);
    lv_obj_add_style(label_104, border_top_btn_17, 0);

    // unnamed: obj_105 (obj)
    lv_obj_t* obj_105 = lv_obj_create(obj_103);

    lv_obj_set_style_layout(obj_105, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_105, s_static_array_4, s_static_array_5);
    lv_obj_add_style(obj_105, container_transp_8, 0);
    lv_obj_set_style_width(obj_105, lv_pct(100), 0);
    lv_obj_set_style_height(obj_105, 1073741823, 0);
    lv_obj_set_style_pad_left(obj_105, 2, 0);
    // unnamed: label_106 (label)
    lv_obj_t* label_106 = lv_label_create(obj_105);

    lv_label_set_text(label_106, "XY");
    lv_obj_set_style_text_font(label_106, font_kode_20_4, 0);
    lv_obj_set_grid_cell(label_106, LV_GRID_ALIGN_START, 0, 1, LV_GRID_ALIGN_START, 0, 1);
    lv_obj_set_style_height(label_106, 1073741823, 0);
    lv_obj_add_flag(label_106, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_106, "cycle_step_xy", 0, NULL, 0, NULL);

    // unnamed: label_107 (label)
    lv_obj_t* label_107 = lv_label_create(obj_105);

    lv_obj_set_grid_cell(label_107, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_107, font_kode_20_4, 0);
    lv_obj_set_style_height(label_107, 1073741823, 0);
    lv_label_set_text(label_107, "10");
    lv_obj_set_style_pad_right(label_107, 10, 0);
    lv_obj_add_style(label_107, indicator_yellow_14, 0);
    lv_obj_add_flag(label_107, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_107, "cycle_step_xy", 0, NULL, 0, NULL);
    data_binding_add_observer("jog_step_xy", label_107, 0, "%g", 0, NULL);

    // unnamed: label_108 (label)
    lv_obj_t* label_108 = lv_label_create(obj_105);

    lv_label_set_text(label_108, "Z");
    lv_obj_set_style_text_font(label_108, font_kode_20_4, 0);
    lv_obj_set_grid_cell(label_108, LV_GRID_ALIGN_START, 2, 1, LV_GRID_ALIGN_START, 0, 1);
    lv_obj_set_style_height(label_108, 1073741823, 0);
    lv_obj_add_flag(label_108, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_108, "cycle_step_z", 0, NULL, 0, NULL);

    // unnamed: label_109 (label)
    lv_obj_t* label_109 = lv_label_create(obj_105);

    lv_obj_set_grid_cell(label_109, LV_GRID_ALIGN_START, 3, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_109, font_kode_20_4, 0);
    lv_obj_set_style_height(label_109, 1073741823, 0);
    lv_label_set_text(label_109, " 5");
    lv_obj_add_style(label_109, indicator_yellow_14, 0);
    lv_obj_add_flag(label_109, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_109, "cycle_step_z", 0, NULL, 0, NULL);
    data_binding_add_observer("jog_step_z", label_109, 0, "%g", 0, NULL);



    // unnamed: obj_110 (obj)
    lv_obj_t* obj_110 = lv_obj_create(obj_102);

    lv_obj_set_style_layout(obj_110, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_110, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_110, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_110, 1073741823, 0);
    lv_obj_set_style_min_width(obj_110, 50, 0);
    lv_obj_set_style_height(obj_110, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_110, 0, 0);
    // unnamed: label_111 (label)
    lv_obj_t* label_111 = lv_label_create(obj_110);

    lv_label_set_text(label_111, "MM");
    lv_obj_set_style_text_font(label_111, font_kode_14_5, 0);
    lv_obj_add_style(label_111, border_top_btn_17, 0);

    // unnamed: label_112 (label)
    lv_obj_t* label_112 = lv_label_create(obj_110);

    lv_label_set_text(label_112, "Jog Ovr");

    // unnamed: label_113 (label)
    lv_obj_t* label_113 = lv_label_create(obj_110);

    lv_obj_set_style_text_font(label_113, font_kode_14_5, 0);
    lv_obj_add_style(label_113, indicator_yellow_14, 0);
    lv_label_set_text(label_113, "100% ");


    data_binding_add_observer("program_running", obj_102, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = false } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = true } } }, 2, NULL);

    // unnamed: obj_114 (obj)
    lv_obj_t* obj_114 = lv_obj_create(obj_73);

    lv_obj_set_style_size(obj_114, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_114, container_transp_8, 0);
    lv_obj_add_style(obj_114, bg_group_25, 0);
    lv_obj_set_style_layout(obj_114, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_114, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_114, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_114, 0, 0);
    lv_obj_set_style_pad_bottom(obj_114, 4, 0);
    lv_obj_set_style_pad_top(obj_114, 4, 0);
    // unnamed: obj_115 (obj)
    lv_obj_t* obj_115 = lv_obj_create(obj_114);

    lv_obj_set_style_layout(obj_115, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_115, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_115, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_115, lv_pct(100), 0);
    lv_obj_set_style_height(obj_115, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_115, 1, 0);
    // unnamed: obj_116 (obj)
    lv_obj_t* obj_116 = lv_obj_create(obj_115);

    lv_obj_set_style_layout(obj_116, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_116, s_static_array_6, s_static_array_7);
    lv_obj_add_style(obj_116, container_transp_8, 0);
    lv_obj_set_style_width(obj_116, lv_pct(100), 0);
    lv_obj_set_style_height(obj_116, 1073741823, 0);
    // unnamed: obj_117 (obj)
    lv_obj_t* obj_117 = lv_obj_create(obj_116);

    lv_obj_set_style_layout(obj_117, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_117, 100, 1073741823, 0);
    lv_obj_add_style(obj_117, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_117, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_117, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_117, 0, 0);
    lv_obj_set_style_pad_bottom(obj_117, -8, 0);
    // unnamed: label_118 (label)
    lv_obj_t* label_118 = lv_label_create(obj_117);

    lv_label_set_text(label_118, "C");
    lv_obj_set_style_text_font(label_118, font_kode_40_0, 0);
    lv_obj_set_style_height(label_118, 1073741823, 0);
    lv_obj_set_style_pad_left(label_118, 5, 0);

    // unnamed: label_119 (label)
    lv_obj_t* label_119 = lv_label_create(obj_117);

    lv_label_set_text(label_119, "Chipload");
    lv_obj_set_style_pad_left(label_119, 0, 0);
    lv_obj_set_style_height(label_119, 1073741823, 0);
    lv_obj_set_style_text_font(label_119, font_kode_14_5, 0);
    lv_obj_add_style(label_119, border_top_btn_17, 0);


    // unnamed: label_120 (label)
    lv_obj_t* label_120 = lv_label_create(obj_116);

    lv_obj_set_grid_cell(label_120, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_120, font_kode_30_2, 0);
    lv_obj_set_style_height(label_120, 1073741823, 0);
    lv_label_set_text(label_120, "1000");
    lv_obj_set_style_pad_right(label_120, 5, 0);
    data_binding_add_observer("chipload_disp", label_120, 0, "%.0f", 0, NULL);


    // unnamed: obj_121 (obj)
    lv_obj_t* obj_121 = lv_obj_create(obj_115);

    lv_obj_set_style_layout(obj_121, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_121, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_121, container_transp_8, 0);
    lv_obj_set_style_width(obj_121, lv_pct(100), 0);
    lv_obj_set_style_height(obj_121, 1073741823, 0);
    // unnamed: bar_122 (bar)
    lv_obj_t* bar_122 = lv_bar_create(obj_121);

    lv_obj_set_style_width(bar_122, lv_pct(100), 0);
    lv_obj_set_style_height(bar_122, 15, 0);
    lv_obj_set_style_margin_left(bar_122, 15, 0);
    lv_obj_set_style_margin_right(bar_122, 15, 0);
    lv_obj_add_style(bar_122, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_122, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_122, 65, 0);
    lv_bar_set_range(bar_122, -50, 150);
    lv_obj_set_style_bg_color(bar_122, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_122, 255, 0);
    data_binding_add_observer("chipload_disp", bar_122, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_123 (scale)
    lv_obj_t* scale_123 = lv_scale_create(obj_121);

    lv_obj_set_style_width(scale_123, lv_pct(100), 0);
    lv_obj_set_style_height(scale_123, 18, 0);
    lv_obj_set_style_margin_left(scale_123, 15, 0);
    lv_obj_set_style_margin_right(scale_123, 15, 0);
    lv_obj_set_style_margin_bottom(scale_123, 2, 0);
    lv_obj_add_style(scale_123, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_123, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_123, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_124 (obj)
    lv_obj_t* obj_124 = lv_obj_create(obj_114);

    lv_obj_set_style_layout(obj_124, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_124, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_124, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_124, 1073741823, 0);
    lv_obj_set_style_min_width(obj_124, 50, 0);
    lv_obj_set_style_height(obj_124, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_124, 0, 0);
    lv_obj_set_style_pad_row(obj_124, 0, 0);
    lv_obj_set_flex_align(obj_124, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_124, LV_OBJ_FLAG_CLICKABLE);
    // unnamed: label_125 (label)
    lv_obj_t* label_125 = lv_label_create(obj_124);

    lv_obj_set_style_text_font(label_125, font_kode_14_5, 0);
    lv_obj_add_style(label_125, indicator_yellow_14, 0);
    data_binding_add_observer("tool_material", label_125, 0, "%s", 0, NULL);

    // unnamed: label_126 (label)
    lv_obj_t* label_126 = lv_label_create(obj_124);

    lv_obj_add_style(label_126, indicator_yellow_14, 0);
    data_binding_add_observer("tool_dia", label_126, 0, "%g mm", 0, NULL);

    // unnamed: label_127 (label)
    lv_obj_t* label_127 = lv_label_create(obj_124);

    lv_obj_set_style_text_font(label_127, font_kode_14_5, 0);
    lv_obj_add_style(label_127, indicator_yellow_14, 0);
    data_binding_add_observer("tool_n_flutes", label_127, 0, "%g-FL", 0, NULL);

    // unnamed: obj_128 (obj)
    lv_obj_t* obj_128 = lv_obj_create(obj_124);

    lv_obj_add_style(obj_128, flex_y_12, 0);
    lv_obj_add_style(obj_128, container_transp_8, 0);
    lv_obj_set_style_size(obj_128, 1073741823, 1073741823, 0);
    lv_obj_set_style_pad_row(obj_128, 0, 0);
    // unnamed: label_129 (label)
    lv_obj_t* label_129 = lv_label_create(obj_128);

    lv_obj_set_style_text_font(label_129, font_kode_14_5, 0);
    data_binding_add_observer("chipload_min", label_129, 0, "%0.2f", 0, NULL);

    // unnamed: label_130 (label)
    lv_obj_t* label_130 = lv_label_create(obj_128);

    lv_obj_set_style_text_font(label_130, font_kode_14_5, 0);
    data_binding_add_observer("chipload_max", label_130, 0, "%0.2f", 0, NULL);



    data_binding_add_observer("program_running", obj_114, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = true } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = false } } }, 2, NULL);




    // unnamed: obj_131 (obj)
    lv_obj_t* obj_131 = lv_tileview_add_tile(tileview_28, 1, 0, LV_DIR_LEFT);

    lv_obj_add_style(obj_131, container_7, 0);
    // unnamed: obj_132 (obj)
    lv_obj_t* obj_132 = lv_obj_create(obj_131);

    lv_obj_add_style(obj_132, container_transp_8, 0);
    lv_obj_add_style(obj_132, flex_x_11, 0);
    lv_obj_set_style_size(obj_132, lv_pct(100), lv_pct(100), 0);
    // unnamed: tabview_133 (tabview)
    lv_obj_t* tabview_133 = lv_tabview_create(obj_132);

    lv_tabview_set_tab_bar_position(tabview_133, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(tabview_133, 40);
    lv_obj_set_style_size(tabview_133, 270, lv_pct(100), 0);
    lv_obj_add_style(tabview_133, container_transp_8, 0);
    lv_obj_add_style(tabview_133, bg_gradient_10, 0);
    // unnamed: obj_134 (obj)
    lv_obj_t* obj_134 = lv_tabview_get_tab_bar(tabview_133);

    lv_obj_add_style(obj_134, container_transp_8, 0);
    lv_obj_add_style(obj_134, bg_gradient_10, 0);

    // unnamed: obj_135 (obj)
    lv_obj_t* obj_135 = lv_tabview_get_content(tabview_133);

    lv_obj_remove_flag(obj_135, LV_OBJ_FLAG_SCROLLABLE);

    // unnamed: obj_136 (obj)
    lv_obj_t* obj_136 = lv_tabview_add_tab(tabview_133, "Inside");

    lv_obj_add_style(obj_136, container_transp_8, 0);
    lv_obj_set_style_size(obj_136, 1073741823, 1073741823, 0);
    lv_obj_remove_flag(obj_136, LV_OBJ_FLAG_SCROLLABLE);
    // unnamed: obj_137 (obj)
    lv_obj_t* obj_137 = lv_obj_create(obj_136);

    lv_obj_add_style(obj_137, container_transp_8, 0);
    lv_obj_add_style(obj_137, bg_gradient_10, 0);
    lv_obj_set_style_size(obj_137, 1073741823, 1073741823, 0);
    // unnamed: obj_138 (obj)
    lv_obj_t* obj_138 = lv_obj_create(obj_137);

    lv_obj_set_style_layout(obj_138, LV_LAYOUT_GRID, 0);
    lv_obj_set_style_size(obj_138, 1073741823, 1073741823, 0);
    lv_obj_add_style(obj_138, container_transp_8, 0);
    lv_obj_add_style(obj_138, bg_group_25, 0);
    lv_obj_set_style_pad_all(obj_138, 10, 0);
    lv_obj_set_grid_dsc_array(obj_138, s_static_array_8, s_static_array_9);
    // unnamed: obj_139 (obj)
    lv_obj_t* obj_139 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_139, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_139, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_139, 80, 80, 0);
    // unnamed: button_140 (button)
    lv_obj_t* button_140 = lv_button_create(obj_139);

    lv_obj_set_style_size(button_140, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_140, container_transp_8, 0);
    lv_obj_set_style_border_width(button_140, 0, 0);
    lv_obj_set_style_outline_width(button_140, 0, 0);
    lv_obj_set_style_shadow_width(button_140, 5, 0);
    lv_obj_set_style_shadow_opa(button_140, 100, 0);
    lv_obj_set_style_shadow_spread(button_140, 3, 0);
    lv_obj_set_style_pad_all(button_140, 5, 0);
    // unnamed: image_141 (image)
    lv_obj_t* image_141 = lv_image_create(button_140);

    lv_image_set_src(image_141, &img_probe_grid_0);



    // unnamed: obj_142 (obj)
    lv_obj_t* obj_142 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_142, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_142, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_142, 80, 80, 0);
    // unnamed: button_143 (button)
    lv_obj_t* button_143 = lv_button_create(obj_142);

    lv_obj_set_style_size(button_143, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_143, container_transp_8, 0);
    lv_obj_set_style_border_width(button_143, 0, 0);
    lv_obj_set_style_outline_width(button_143, 0, 0);
    lv_obj_set_style_shadow_width(button_143, 5, 0);
    lv_obj_set_style_shadow_opa(button_143, 100, 0);
    lv_obj_set_style_shadow_spread(button_143, 3, 0);
    lv_obj_set_style_pad_all(button_143, 5, 0);
    // unnamed: image_144 (image)
    lv_obj_t* image_144 = lv_image_create(button_143);

    lv_image_set_src(image_144, &img_probe_grid_1);



    // unnamed: obj_145 (obj)
    lv_obj_t* obj_145 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_145, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_145, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_145, 80, 80, 0);
    // unnamed: button_146 (button)
    lv_obj_t* button_146 = lv_button_create(obj_145);

    lv_obj_set_style_size(button_146, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_146, container_transp_8, 0);
    lv_obj_set_style_border_width(button_146, 0, 0);
    lv_obj_set_style_outline_width(button_146, 0, 0);
    lv_obj_set_style_shadow_width(button_146, 5, 0);
    lv_obj_set_style_shadow_opa(button_146, 100, 0);
    lv_obj_set_style_shadow_spread(button_146, 3, 0);
    lv_obj_set_style_pad_all(button_146, 5, 0);
    // unnamed: image_147 (image)
    lv_obj_t* image_147 = lv_image_create(button_146);

    lv_image_set_src(image_147, &img_probe_grid_2);



    // unnamed: obj_148 (obj)
    lv_obj_t* obj_148 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_148, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_148, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_148, 80, 80, 0);
    // unnamed: button_149 (button)
    lv_obj_t* button_149 = lv_button_create(obj_148);

    lv_obj_set_style_size(button_149, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_149, container_transp_8, 0);
    lv_obj_set_style_border_width(button_149, 0, 0);
    lv_obj_set_style_outline_width(button_149, 0, 0);
    lv_obj_set_style_shadow_width(button_149, 5, 0);
    lv_obj_set_style_shadow_opa(button_149, 100, 0);
    lv_obj_set_style_shadow_spread(button_149, 3, 0);
    lv_obj_set_style_pad_all(button_149, 5, 0);
    // unnamed: image_150 (image)
    lv_obj_t* image_150 = lv_image_create(button_149);

    lv_image_set_src(image_150, &img_probe_grid_3);



    // unnamed: obj_151 (obj)
    lv_obj_t* obj_151 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_151, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_151, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_151, 80, 80, 0);
    // unnamed: button_152 (button)
    lv_obj_t* button_152 = lv_button_create(obj_151);

    lv_obj_set_style_size(button_152, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_152, container_transp_8, 0);
    lv_obj_set_style_border_width(button_152, 0, 0);
    lv_obj_set_style_outline_width(button_152, 0, 0);
    lv_obj_set_style_shadow_width(button_152, 5, 0);
    lv_obj_set_style_shadow_opa(button_152, 100, 0);
    lv_obj_set_style_shadow_spread(button_152, 3, 0);
    lv_obj_set_style_pad_all(button_152, 5, 0);
    // unnamed: image_153 (image)
    lv_obj_t* image_153 = lv_image_create(button_152);

    lv_image_set_src(image_153, &img_probe_grid_4);



    // unnamed: obj_154 (obj)
    lv_obj_t* obj_154 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_154, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_154, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_154, 80, 80, 0);
    // unnamed: button_155 (button)
    lv_obj_t* button_155 = lv_button_create(obj_154);

    lv_obj_set_style_size(button_155, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_155, container_transp_8, 0);
    lv_obj_set_style_border_width(button_155, 0, 0);
    lv_obj_set_style_outline_width(button_155, 0, 0);
    lv_obj_set_style_shadow_width(button_155, 5, 0);
    lv_obj_set_style_shadow_opa(button_155, 100, 0);
    lv_obj_set_style_shadow_spread(button_155, 3, 0);
    lv_obj_set_style_pad_all(button_155, 5, 0);
    // unnamed: image_156 (image)
    lv_obj_t* image_156 = lv_image_create(button_155);

    lv_image_set_src(image_156, &img_probe_grid_5);



    // unnamed: obj_157 (obj)
    lv_obj_t* obj_157 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_157, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_157, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_157, 80, 80, 0);
    // unnamed: button_158 (button)
    lv_obj_t* button_158 = lv_button_create(obj_157);

    lv_obj_set_style_size(button_158, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_158, container_transp_8, 0);
    lv_obj_set_style_border_width(button_158, 0, 0);
    lv_obj_set_style_outline_width(button_158, 0, 0);
    lv_obj_set_style_shadow_width(button_158, 5, 0);
    lv_obj_set_style_shadow_opa(button_158, 100, 0);
    lv_obj_set_style_shadow_spread(button_158, 3, 0);
    lv_obj_set_style_pad_all(button_158, 5, 0);
    // unnamed: image_159 (image)
    lv_obj_t* image_159 = lv_image_create(button_158);

    lv_image_set_src(image_159, &img_probe_grid_6);



    // unnamed: obj_160 (obj)
    lv_obj_t* obj_160 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_160, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_160, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_160, 80, 80, 0);
    // unnamed: button_161 (button)
    lv_obj_t* button_161 = lv_button_create(obj_160);

    lv_obj_set_style_size(button_161, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_161, container_transp_8, 0);
    lv_obj_set_style_border_width(button_161, 0, 0);
    lv_obj_set_style_outline_width(button_161, 0, 0);
    lv_obj_set_style_shadow_width(button_161, 5, 0);
    lv_obj_set_style_shadow_opa(button_161, 100, 0);
    lv_obj_set_style_shadow_spread(button_161, 3, 0);
    lv_obj_set_style_pad_all(button_161, 5, 0);
    // unnamed: image_162 (image)
    lv_obj_t* image_162 = lv_image_create(button_161);

    lv_image_set_src(image_162, &img_probe_grid_7);



    // unnamed: obj_163 (obj)
    lv_obj_t* obj_163 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_163, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_163, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_163, 80, 80, 0);
    // unnamed: button_164 (button)
    lv_obj_t* button_164 = lv_button_create(obj_163);

    lv_obj_set_style_size(button_164, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_164, container_transp_8, 0);
    lv_obj_set_style_border_width(button_164, 0, 0);
    lv_obj_set_style_outline_width(button_164, 0, 0);
    lv_obj_set_style_shadow_width(button_164, 5, 0);
    lv_obj_set_style_shadow_opa(button_164, 100, 0);
    lv_obj_set_style_shadow_spread(button_164, 3, 0);
    lv_obj_set_style_pad_all(button_164, 5, 0);
    // unnamed: image_165 (image)
    lv_obj_t* image_165 = lv_image_create(button_164);

    lv_image_set_src(image_165, &img_probe_grid_8);






    // unnamed: obj_166 (obj)
    lv_obj_t* obj_166 = lv_tabview_add_tab(tabview_133, "Outside");

    lv_obj_add_style(obj_166, container_transp_8, 0);
    lv_obj_set_style_size(obj_166, 1073741823, 1073741823, 0);
    // unnamed: obj_167 (obj)
    lv_obj_t* obj_167 = lv_obj_create(obj_166);

    lv_obj_add_style(obj_167, container_transp_8, 0);
    lv_obj_add_style(obj_167, bg_gradient_10, 0);
    lv_obj_set_style_size(obj_167, 1073741823, 1073741823, 0);
    // unnamed: obj_168 (obj)
    lv_obj_t* obj_168 = lv_obj_create(obj_167);

    lv_obj_set_style_layout(obj_168, LV_LAYOUT_GRID, 0);
    lv_obj_set_style_size(obj_168, 1073741823, 1073741823, 0);
    lv_obj_add_style(obj_168, container_transp_8, 0);
    lv_obj_add_style(obj_168, bg_group_25, 0);
    lv_obj_set_style_pad_all(obj_168, 10, 0);
    lv_obj_set_grid_dsc_array(obj_168, s_static_array_10, s_static_array_11);
    // unnamed: obj_169 (obj)
    lv_obj_t* obj_169 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_169, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_169, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_169, 80, 80, 0);
    // unnamed: button_170 (button)
    lv_obj_t* button_170 = lv_button_create(obj_169);

    lv_obj_set_style_size(button_170, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_170, container_transp_8, 0);
    lv_obj_set_style_border_width(button_170, 0, 0);
    lv_obj_set_style_outline_width(button_170, 0, 0);
    lv_obj_set_style_shadow_width(button_170, 5, 0);
    lv_obj_set_style_shadow_opa(button_170, 100, 0);
    lv_obj_set_style_shadow_spread(button_170, 3, 0);
    lv_obj_set_style_pad_all(button_170, 5, 0);
    // unnamed: image_171 (image)
    lv_obj_t* image_171 = lv_image_create(button_170);

    lv_image_set_src(image_171, &img_probe_out_0);



    // unnamed: obj_172 (obj)
    lv_obj_t* obj_172 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_172, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_172, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_172, 80, 80, 0);
    // unnamed: button_173 (button)
    lv_obj_t* button_173 = lv_button_create(obj_172);

    lv_obj_set_style_size(button_173, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_173, container_transp_8, 0);
    lv_obj_set_style_border_width(button_173, 0, 0);
    lv_obj_set_style_outline_width(button_173, 0, 0);
    lv_obj_set_style_shadow_width(button_173, 5, 0);
    lv_obj_set_style_shadow_opa(button_173, 100, 0);
    lv_obj_set_style_shadow_spread(button_173, 3, 0);
    lv_obj_set_style_pad_all(button_173, 5, 0);
    // unnamed: image_174 (image)
    lv_obj_t* image_174 = lv_image_create(button_173);

    lv_image_set_src(image_174, &img_probe_out_1);



    // unnamed: obj_175 (obj)
    lv_obj_t* obj_175 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_175, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_175, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_175, 80, 80, 0);
    // unnamed: button_176 (button)
    lv_obj_t* button_176 = lv_button_create(obj_175);

    lv_obj_set_style_size(button_176, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_176, container_transp_8, 0);
    lv_obj_set_style_border_width(button_176, 0, 0);
    lv_obj_set_style_outline_width(button_176, 0, 0);
    lv_obj_set_style_shadow_width(button_176, 5, 0);
    lv_obj_set_style_shadow_opa(button_176, 100, 0);
    lv_obj_set_style_shadow_spread(button_176, 3, 0);
    lv_obj_set_style_pad_all(button_176, 5, 0);
    // unnamed: image_177 (image)
    lv_obj_t* image_177 = lv_image_create(button_176);

    lv_image_set_src(image_177, &img_probe_out_2);



    // unnamed: obj_178 (obj)
    lv_obj_t* obj_178 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_178, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_178, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_178, 80, 80, 0);
    // unnamed: button_179 (button)
    lv_obj_t* button_179 = lv_button_create(obj_178);

    lv_obj_set_style_size(button_179, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_179, container_transp_8, 0);
    lv_obj_set_style_border_width(button_179, 0, 0);
    lv_obj_set_style_outline_width(button_179, 0, 0);
    lv_obj_set_style_shadow_width(button_179, 5, 0);
    lv_obj_set_style_shadow_opa(button_179, 100, 0);
    lv_obj_set_style_shadow_spread(button_179, 3, 0);
    lv_obj_set_style_pad_all(button_179, 5, 0);
    // unnamed: image_180 (image)
    lv_obj_t* image_180 = lv_image_create(button_179);

    lv_image_set_src(image_180, &img_probe_out_3);



    // unnamed: obj_181 (obj)
    lv_obj_t* obj_181 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_181, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_181, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_181, 80, 80, 0);
    // unnamed: button_182 (button)
    lv_obj_t* button_182 = lv_button_create(obj_181);

    lv_obj_set_style_size(button_182, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_182, container_transp_8, 0);
    lv_obj_set_style_border_width(button_182, 0, 0);
    lv_obj_set_style_outline_width(button_182, 0, 0);
    lv_obj_set_style_shadow_width(button_182, 5, 0);
    lv_obj_set_style_shadow_opa(button_182, 100, 0);
    lv_obj_set_style_shadow_spread(button_182, 3, 0);
    lv_obj_set_style_pad_all(button_182, 5, 0);
    // unnamed: image_183 (image)
    lv_obj_t* image_183 = lv_image_create(button_182);

    lv_image_set_src(image_183, &img_probe_out_4);



    // unnamed: obj_184 (obj)
    lv_obj_t* obj_184 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_184, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_184, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_184, 80, 80, 0);
    // unnamed: button_185 (button)
    lv_obj_t* button_185 = lv_button_create(obj_184);

    lv_obj_set_style_size(button_185, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_185, container_transp_8, 0);
    lv_obj_set_style_border_width(button_185, 0, 0);
    lv_obj_set_style_outline_width(button_185, 0, 0);
    lv_obj_set_style_shadow_width(button_185, 5, 0);
    lv_obj_set_style_shadow_opa(button_185, 100, 0);
    lv_obj_set_style_shadow_spread(button_185, 3, 0);
    lv_obj_set_style_pad_all(button_185, 5, 0);
    // unnamed: image_186 (image)
    lv_obj_t* image_186 = lv_image_create(button_185);

    lv_image_set_src(image_186, &img_probe_out_5);



    // unnamed: obj_187 (obj)
    lv_obj_t* obj_187 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_187, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_187, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_187, 80, 80, 0);
    // unnamed: button_188 (button)
    lv_obj_t* button_188 = lv_button_create(obj_187);

    lv_obj_set_style_size(button_188, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_188, container_transp_8, 0);
    lv_obj_set_style_border_width(button_188, 0, 0);
    lv_obj_set_style_outline_width(button_188, 0, 0);
    lv_obj_set_style_shadow_width(button_188, 5, 0);
    lv_obj_set_style_shadow_opa(button_188, 100, 0);
    lv_obj_set_style_shadow_spread(button_188, 3, 0);
    lv_obj_set_style_pad_all(button_188, 5, 0);
    // unnamed: image_189 (image)
    lv_obj_t* image_189 = lv_image_create(button_188);

    lv_image_set_src(image_189, &img_probe_out_6);



    // unnamed: obj_190 (obj)
    lv_obj_t* obj_190 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_190, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_190, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_190, 80, 80, 0);
    // unnamed: button_191 (button)
    lv_obj_t* button_191 = lv_button_create(obj_190);

    lv_obj_set_style_size(button_191, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_191, container_transp_8, 0);
    lv_obj_set_style_border_width(button_191, 0, 0);
    lv_obj_set_style_outline_width(button_191, 0, 0);
    lv_obj_set_style_shadow_width(button_191, 5, 0);
    lv_obj_set_style_shadow_opa(button_191, 100, 0);
    lv_obj_set_style_shadow_spread(button_191, 3, 0);
    lv_obj_set_style_pad_all(button_191, 5, 0);
    // unnamed: image_192 (image)
    lv_obj_t* image_192 = lv_image_create(button_191);

    lv_image_set_src(image_192, &img_probe_out_7);



    // unnamed: obj_193 (obj)
    lv_obj_t* obj_193 = lv_obj_create(obj_168);

    lv_obj_add_style(obj_193, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_193, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_193, 80, 80, 0);
    // unnamed: button_194 (button)
    lv_obj_t* button_194 = lv_button_create(obj_193);

    lv_obj_set_style_size(button_194, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_194, container_transp_8, 0);
    lv_obj_set_style_border_width(button_194, 0, 0);
    lv_obj_set_style_outline_width(button_194, 0, 0);
    lv_obj_set_style_shadow_width(button_194, 5, 0);
    lv_obj_set_style_shadow_opa(button_194, 100, 0);
    lv_obj_set_style_shadow_spread(button_194, 3, 0);
    lv_obj_set_style_pad_all(button_194, 5, 0);
    // unnamed: image_195 (image)
    lv_obj_t* image_195 = lv_image_create(button_194);

    lv_image_set_src(image_195, &img_probe_out_8);






    // unnamed: obj_196 (obj)
    lv_obj_t* obj_196 = lv_tabview_add_tab(tabview_133, "Misc");


    // unnamed: obj_197 (obj)
    lv_obj_t* obj_197 = lv_obj_create(obj_132);

    lv_obj_add_style(obj_197, container_transp_8, 0);
    lv_obj_add_style(obj_197, bg_gradient_10, 0);
    lv_obj_add_style(obj_197, flex_y_12, 0);
    lv_obj_set_style_size(obj_197, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_row(obj_197, 8, 0);
    lv_obj_set_style_pad_all(obj_197, 10, 0);
    lv_obj_set_style_flex_grow(obj_197, 1, 0);
    // unnamed: obj_198 (obj)
    lv_obj_t* obj_198 = lv_obj_create(obj_197);

    lv_obj_add_style(obj_198, container_transp_8, 0);
    lv_obj_add_style(obj_198, flex_x_11, 0);
    lv_obj_add_style(obj_198, bg_group_25, 0);
    lv_obj_set_style_size(obj_198, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_198, 3, 0);
    // unnamed: label_199 (label)
    lv_obj_t* label_199 = lv_label_create(obj_198);

    lv_obj_set_style_flex_grow(label_199, 5, 0);
    lv_label_set_text(label_199, "Width / Radius:");

    // unnamed: label_200 (label)
    lv_obj_t* label_200 = lv_label_create(obj_198);

    lv_obj_add_style(label_200, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_200, 2, 0);
    lv_label_set_text(label_200, "100 mm");
    data_binding_add_observer("probe_w", label_200, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_200, "set_probe_width", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);


    // unnamed: obj_201 (obj)
    lv_obj_t* obj_201 = lv_obj_create(obj_197);

    lv_obj_add_style(obj_201, container_transp_8, 0);
    lv_obj_add_style(obj_201, flex_x_11, 0);
    lv_obj_add_style(obj_201, bg_group_25, 0);
    lv_obj_set_style_size(obj_201, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_201, 3, 0);
    // unnamed: label_202 (label)
    lv_obj_t* label_202 = lv_label_create(obj_201);

    lv_obj_set_style_flex_grow(label_202, 5, 0);
    lv_label_set_text(label_202, "Height:");

    // unnamed: label_203 (label)
    lv_obj_t* label_203 = lv_label_create(obj_201);

    lv_obj_add_style(label_203, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_203, 2, 0);
    lv_label_set_text(label_203, "100 mm");
    data_binding_add_observer("probe_h", label_203, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_203, "set_probe_height", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);


    // unnamed: obj_204 (obj)
    lv_obj_t* obj_204 = lv_obj_create(obj_197);

    lv_obj_add_style(obj_204, container_transp_8, 0);
    lv_obj_add_style(obj_204, flex_x_11, 0);
    lv_obj_add_style(obj_204, bg_group_25, 0);
    lv_obj_set_style_size(obj_204, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_204, 3, 0);
    // unnamed: label_205 (label)
    lv_obj_t* label_205 = lv_label_create(obj_204);

    lv_obj_set_style_flex_grow(label_205, 5, 0);
    lv_label_set_text(label_205, "Clearance:");

    // unnamed: label_206 (label)
    lv_obj_t* label_206 = lv_label_create(obj_204);

    lv_obj_add_style(label_206, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_206, 2, 0);
    lv_label_set_text(label_206, "5 mm");
    data_binding_add_observer("probe_cl", label_206, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_206, "set_probe_cl", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);


    // unnamed: obj_207 (obj)
    lv_obj_t* obj_207 = lv_obj_create(obj_197);

    lv_obj_add_style(obj_207, container_transp_8, 0);
    lv_obj_add_style(obj_207, flex_x_11, 0);
    lv_obj_add_style(obj_207, bg_group_25, 0);
    lv_obj_set_style_size(obj_207, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_207, 3, 0);
    // unnamed: label_208 (label)
    lv_obj_t* label_208 = lv_label_create(obj_207);

    lv_obj_set_style_flex_grow(label_208, 5, 0);
    lv_label_set_text(label_208, "Overtravel:");

    // unnamed: label_209 (label)
    lv_obj_t* label_209 = lv_label_create(obj_207);

    lv_obj_add_style(label_209, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_209, 2, 0);
    lv_label_set_text(label_209, "2 mm");
    data_binding_add_observer("probe_ov", label_209, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_209, "set_probe_ov", 3, /* UNMAPPED_ARRAY */ NULL, 5, NULL);


    // unnamed: obj_210 (obj)
    lv_obj_t* obj_210 = lv_obj_create(obj_197);

    lv_obj_add_style(obj_210, container_transp_8, 0);
    lv_obj_add_style(obj_210, flex_x_11, 0);
    lv_obj_add_style(obj_210, bg_group_25, 0);
    lv_obj_set_style_size(obj_210, lv_pct(100), 1073741823, 0);
    lv_obj_set_flex_align(obj_210, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_all(obj_210, 3, 0);
    // unnamed: label_211 (label)
    lv_obj_t* label_211 = lv_label_create(obj_210);

    lv_label_set_text(label_211, "Quick Mode:");
    lv_obj_set_style_flex_grow(label_211, 5, 0);

    // unnamed: switch_212 (switch)
    lv_obj_t* switch_212 = lv_switch_create(obj_210);

    lv_obj_set_style_height(switch_212, 20, 0);
    lv_obj_set_style_width(switch_212, 40, 0);
    lv_obj_set_style_margin_right(switch_212, 10, 0);
    data_binding_add_action(switch_212, "set_probe_quick", 1, NULL, 0, NULL);
    data_binding_add_observer("probe_quick", switch_212, 3, "value.bool", 0, NULL);






}
