/* AUTO-GENERATED by the 'c_code' backend */

#include "lvgl.h"
#include "lvgl_ui.h"
#include <stdlib.h> // For malloc
                    //

#include "ui/assets.h"

void create_ui(lv_obj_t* parent) {
    // --- Static Arrays for LVGL properties ---
    static const int32_t s_static_array_13[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_12[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_11[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_10[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_9[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_8[] = { 160, 160, 160, 536870911 };
    static const int32_t s_static_array_7[] = { 536870810, 536870911 };
    static const int32_t s_static_array_6[] = { 536870810, 536870812, 536870911 };
    static const int32_t s_static_array_5[] = { 536870810, 536870911 };
    static const int32_t s_static_array_4[] = { 22, 50, 12, 50, 536870911 };
    static const int32_t s_static_array_3[] = { 536870810, 536870911 };
    static const int32_t s_static_array_2[] = { 536870810, 536870812, 536870911 };
    static const int32_t s_static_array_1[] = { 536870810, 536870911 };
    static const int32_t s_static_array_0[] = { 536870810, 536870812, 536870911 };

    // font_kode_40: font_kode_40_0 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_40_0 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 40);
    #else
    extern const lv_font_t font_kode_40;
    const lv_font_t* font_kode_40_0 = &font_kode_40;
    #endif

    // font_kode_34: font_kode_34_1 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_34_1 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 34);
    #else
    extern const lv_font_t font_kode_34;
    const lv_font_t* font_kode_34_1 = &font_kode_34;
    #endif

    // font_kode_30: font_kode_30_2 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_30_2 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 30);
    #else
    extern const lv_font_t font_kode_30;
    const lv_font_t* font_kode_30_2 = &font_kode_30;
    #endif

    // font_kode_24: font_kode_24_3 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_24_3 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 24);
    #else
    extern const lv_font_t font_kode_24;
    const lv_font_t* font_kode_24_3 = &font_kode_24;
    #endif

    // font_kode_20: font_kode_20_4 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_20_4 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 20);
    #else
    extern const lv_font_t font_kode_20;
    const lv_font_t* font_kode_20_4 = &font_kode_20;
    #endif

    // font_kode_14: font_kode_14_5 (font)
    #ifdef LOAD_FONTS_TTF
    const lv_font_t* font_kode_14_5 = lv_tiny_ttf_create_file("S:/Users/loranttoth/Development/SW/CNC/lvgl_ui/examples/fonts/kodemono-medium.ttf", 14);
    #else
    extern const lv_font_t font_kode_14;
    const lv_font_t* font_kode_14_5 = &font_kode_14;
    #endif

    // debug: debug_6 (style)
    lv_style_t* debug_6 = malloc(sizeof(lv_style_t));

    lv_style_init(debug_6);
    obj_registry_add("debug", debug_6);
    lv_style_set_outline_width(debug_6, 1);
    lv_style_set_outline_color(debug_6, lv_color_hex(0xFFEEFF));
    lv_style_set_outline_opa(debug_6, 150);
    lv_style_set_border_width(debug_6, 1);
    lv_style_set_border_color(debug_6, lv_color_hex(0xFFEEFF));
    lv_style_set_border_opa(debug_6, 150);
    lv_style_set_radius(debug_6, 0);

    // container: container_7 (style)
    lv_style_t* container_7 = malloc(sizeof(lv_style_t));

    lv_style_init(container_7);
    obj_registry_add("container", container_7);
    lv_style_set_pad_all(container_7, 0);
    lv_style_set_margin_all(container_7, 0);
    lv_style_set_border_width(container_7, 0);
    lv_style_set_pad_row(container_7, 3);
    lv_style_set_pad_column(container_7, 5);
    lv_style_set_bg_color(container_7, lv_color_hex(0x222222));
    lv_style_set_text_color(container_7, lv_color_hex(0xEBEBCB));
    lv_style_set_radius(container_7, 0);

    // container_transp: container_transp_8 (style)
    lv_style_t* container_transp_8 = malloc(sizeof(lv_style_t));

    lv_style_init(container_transp_8);
    obj_registry_add("container_transp", container_transp_8);
    lv_style_set_pad_all(container_transp_8, 0);
    lv_style_set_margin_all(container_transp_8, 0);
    lv_style_set_border_width(container_transp_8, 0);
    lv_style_set_pad_row(container_transp_8, 3);
    lv_style_set_pad_column(container_transp_8, 5);
    lv_style_set_bg_color(container_transp_8, lv_color_hex(0x222222));
    lv_style_set_text_color(container_transp_8, lv_color_hex(0xEBEBCB));
    lv_style_set_radius(container_transp_8, 0);
    lv_style_set_bg_opa(container_transp_8, 0);

    // bar_indicator: bar_indicator_9 (style)
    lv_style_t* bar_indicator_9 = malloc(sizeof(lv_style_t));

    lv_style_init(bar_indicator_9);
    obj_registry_add("bar_indicator", bar_indicator_9);
    lv_style_set_radius(bar_indicator_9, 4);

    // bg_gradient: bg_gradient_10 (style)
    lv_style_t* bg_gradient_10 = malloc(sizeof(lv_style_t));

    lv_style_init(bg_gradient_10);
    obj_registry_add("bg_gradient", bg_gradient_10);
    lv_style_set_bg_opa(bg_gradient_10, 255);
    lv_style_set_bg_color(bg_gradient_10, lv_color_hex(0x222222));
    lv_style_set_bg_grad_color(bg_gradient_10, lv_color_hex(0x444444));
    lv_style_set_bg_grad_dir(bg_gradient_10, LV_GRAD_DIR_HOR);

    // flex_x: flex_x_11 (style)
    lv_style_t* flex_x_11 = malloc(sizeof(lv_style_t));

    lv_style_init(flex_x_11);
    obj_registry_add("flex_x", flex_x_11);
    lv_style_set_layout(flex_x_11, LV_LAYOUT_FLEX);
    lv_style_set_flex_flow(flex_x_11, LV_FLEX_FLOW_ROW);

    // flex_y: flex_y_12 (style)
    lv_style_t* flex_y_12 = malloc(sizeof(lv_style_t));

    lv_style_init(flex_y_12);
    obj_registry_add("flex_y", flex_y_12);
    lv_style_set_layout(flex_y_12, LV_LAYOUT_FLEX);
    lv_style_set_flex_flow(flex_y_12, LV_FLEX_FLOW_COLUMN);

    // indicator_green: indicator_green_13 (style)
    lv_style_t* indicator_green_13 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_green_13);
    obj_registry_add("indicator_green", indicator_green_13);
    lv_style_set_text_color(indicator_green_13, lv_color_hex(0x44EE44));

    // indicator_yellow: indicator_yellow_14 (style)
    lv_style_t* indicator_yellow_14 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_yellow_14);
    obj_registry_add("indicator_yellow", indicator_yellow_14);
    lv_style_set_text_color(indicator_yellow_14, lv_color_hex(0xFFFF55));

    // text_actionable: text_actionable_15 (style)
    lv_style_t* text_actionable_15 = malloc(sizeof(lv_style_t));

    lv_style_init(text_actionable_15);
    obj_registry_add("text_actionable", text_actionable_15);
    lv_style_set_text_color(text_actionable_15, lv_color_hex(0xFFFF55));
    lv_style_set_text_font(text_actionable_15, font_kode_14_5);

    // jog_btn: jog_btn_16 (style)
    lv_style_t* jog_btn_16 = malloc(sizeof(lv_style_t));

    lv_style_init(jog_btn_16);
    obj_registry_add("jog_btn", jog_btn_16);
    lv_style_set_pad_all(jog_btn_16, 5);
    lv_style_set_pad_bottom(jog_btn_16, 10);
    lv_style_set_pad_top(jog_btn_16, 10);
    lv_style_set_margin_all(jog_btn_16, 0);
    lv_style_set_radius(jog_btn_16, 2);

    // border_top_btn: border_top_btn_17 (style)
    lv_style_t* border_top_btn_17 = malloc(sizeof(lv_style_t));

    lv_style_init(border_top_btn_17);
    obj_registry_add("border_top_btn", border_top_btn_17);
    lv_style_set_border_width(border_top_btn_17, 1);
    lv_style_set_border_color(border_top_btn_17, lv_color_hex(0xFFFFFF));
    lv_style_set_border_opa(border_top_btn_17, 50);
    lv_style_set_border_side(border_top_btn_17, 3);

    // border_right: border_right_18 (style)
    lv_style_t* border_right_18 = malloc(sizeof(lv_style_t));

    lv_style_init(border_right_18);
    obj_registry_add("border_right", border_right_18);
    lv_style_set_border_width(border_right_18, 1);
    lv_style_set_border_color(border_right_18, lv_color_hex(0xFFFFFF));
    lv_style_set_border_opa(border_right_18, 50);
    lv_style_set_border_side(border_right_18, LV_BORDER_SIDE_RIGHT);

    // indicator_light: indicator_light_19 (style)
    lv_style_t* indicator_light_19 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_19);
    obj_registry_add("indicator_light", indicator_light_19);
    lv_style_set_border_width(indicator_light_19, 6);
    lv_style_set_pad_left(indicator_light_19, 12);
    lv_style_set_margin_left(indicator_light_19, 5);
    lv_style_set_border_opa(indicator_light_19, 200);
    lv_style_set_border_side(indicator_light_19, LV_BORDER_SIDE_LEFT);

    // indicator_light_red: indicator_light_red_20 (style)
    lv_style_t* indicator_light_red_20 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_red_20);
    obj_registry_add("indicator_light_red", indicator_light_red_20);
    lv_style_set_border_color(indicator_light_red_20, lv_color_hex(0xFF5555));

    // indicator_light_green: indicator_light_green_21 (style)
    lv_style_t* indicator_light_green_21 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_green_21);
    obj_registry_add("indicator_light_green", indicator_light_green_21);
    lv_style_set_border_color(indicator_light_green_21, lv_color_hex(0x55FF55));

    // indicator_light_yellow: indicator_light_yellow_22 (style)
    lv_style_t* indicator_light_yellow_22 = malloc(sizeof(lv_style_t));

    lv_style_init(indicator_light_yellow_22);
    obj_registry_add("indicator_light_yellow", indicator_light_yellow_22);
    lv_style_set_border_color(indicator_light_yellow_22, lv_color_hex(0xFFFF55));

    // debug: debug_23 (style)
    lv_style_t* debug_23 = malloc(sizeof(lv_style_t));

    lv_style_init(debug_23);
    obj_registry_add("debug", debug_23);
    lv_style_set_bg_color(debug_23, lv_color_hex(0xF000F0));
    lv_style_set_bg_opa(debug_23, LV_OPA_COVER);

    // btn_clicked: btn_clicked_24 (style)
    lv_style_t* btn_clicked_24 = malloc(sizeof(lv_style_t));

    lv_style_init(btn_clicked_24);
    obj_registry_add("btn_clicked", btn_clicked_24);
    lv_style_set_bg_color(btn_clicked_24, lv_color_hex(0x777777));
    lv_style_set_bg_opa(btn_clicked_24, 60);

    // bg_group: bg_group_25 (style)
    lv_style_t* bg_group_25 = malloc(sizeof(lv_style_t));

    lv_style_init(bg_group_25);
    obj_registry_add("bg_group", bg_group_25);
    lv_style_set_bg_opa(bg_group_25, 40);
    lv_style_set_bg_color(bg_group_25, lv_color_hex(0x111111));

    // tick_color: tick_color_26 (style)
    lv_style_t* tick_color_26 = malloc(sizeof(lv_style_t));

    lv_style_init(tick_color_26);
    obj_registry_add("tick_color", tick_color_26);
    lv_style_set_line_color(tick_color_26, lv_color_hex(0x777777));

    // background_purple: background_purple_27 (style)
    lv_style_t* background_purple_27 = malloc(sizeof(lv_style_t));

    lv_style_init(background_purple_27);
    obj_registry_add("background_purple", background_purple_27);
    lv_style_set_text_color(background_purple_27, lv_color_hex(0xFF00FF));

    // background_none: background_none_28 (style)
    lv_style_t* background_none_28 = malloc(sizeof(lv_style_t));

    lv_style_init(background_none_28);
    obj_registry_add("background_none", background_none_28);
    lv_style_set_shadow_opa(background_none_28, 0);
    lv_style_set_bg_opa(background_none_28, 0);

    // unnamed: obj_29 (obj)
    lv_obj_t* obj_29 = lv_screen_active();

    lv_obj_add_style(obj_29, container_7, 0);

    // unnamed: tileview_30 (tileview)
    lv_obj_t* tileview_30 = lv_tileview_create(parent);

    lv_obj_add_style(tileview_30, container_7, 0);
    lv_obj_set_style_size(tileview_30, lv_pct(100), lv_pct(100), 0);
    lv_obj_set_style_pad_row(tileview_30, 0, 0);
    lv_obj_set_style_pad_column(tileview_30, 0, 0);
    lv_obj_set_scrollbar_mode(tileview_30, LV_SCROLLBAR_MODE_ACTIVE);
    // unnamed: obj_31 (obj)
    lv_obj_t* obj_31 = lv_tileview_add_tile(tileview_30, 0, 0, LV_DIR_RIGHT);

    lv_obj_add_style(obj_31, container_7, 0);
    // main: main_32 (obj)
    lv_obj_t* main_32 = lv_obj_create(obj_31);

    obj_registry_add("main", main_32);
    lv_obj_set_style_layout(main_32, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(main_32, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_flex_align(main_32, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_style(main_32, container_7, 0);
    lv_obj_set_style_size(main_32, lv_pct(100), lv_pct(100), 0);
    lv_obj_remove_flag(main_32, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_border_width(main_32, 0, 0);
    lv_obj_set_style_pad_all(main_32, 0, 0);
    lv_obj_set_style_margin_all(main_32, 0, 0);
    lv_obj_set_style_outline_width(main_32, 0, 0);
    // unnamed: obj_33 (obj)
    lv_obj_t* obj_33 = lv_obj_create(main_32);

    lv_obj_set_style_layout(obj_33, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_33, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_33, container_7, 0);
    lv_obj_set_style_height(obj_33, lv_pct(100), 0);
    lv_obj_set_style_flex_grow(obj_33, 4, 0);
    lv_obj_set_style_border_side(obj_33, LV_BORDER_SIDE_RIGHT, 0);
    lv_obj_set_style_border_width(obj_33, 1, 0);
    lv_obj_set_style_radius(obj_33, 0, 0);
    lv_obj_set_style_border_color(obj_33, lv_color_hex(0x333333), 0);
    lv_obj_set_style_border_opa(obj_33, 255, 0);
    // unnamed: obj_34 (obj)
    lv_obj_t* obj_34 = lv_obj_create(obj_33);

    lv_obj_set_style_size(obj_34, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_34, container_7, 0);
    lv_obj_add_style(obj_34, flex_y_12, 0);
    lv_obj_add_style(obj_34, bg_gradient_10, 0);
    lv_obj_set_style_bg_opa(obj_34, 255, 0);
    lv_obj_set_style_pad_column(obj_34, 0, 0);
    lv_obj_set_style_pad_row(obj_34, 0, 0);
    lv_obj_remove_flag(obj_34, LV_OBJ_FLAG_SCROLLABLE);
    // $name: __name_35 (obj)
    lv_obj_t* __name_35 = lv_obj_create(obj_34);

    obj_registry_add("$name", __name_35);
    lv_obj_add_style(__name_35, flex_x_11, 0);
    lv_obj_add_style(__name_35, container_transp_8, 0);
    lv_obj_add_style(__name_35, bg_group_25, 0);
    lv_obj_set_style_size(__name_35, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_35, 10, 0);
    lv_obj_set_style_pad_bottom(__name_35, 18, 0);
    lv_obj_set_style_border_color(__name_35, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_35, 40, 0);
    lv_obj_set_style_margin_all(__name_35, 2, 0);
    // unnamed: button_36 (button)
    lv_obj_t* button_36 = lv_button_create(__name_35);

    lv_obj_set_style_text_font(button_36, font_kode_40_0, 0);
    lv_obj_set_style_width(button_36, 35, 0);
    lv_obj_add_style(button_36, indicator_light_19, 0);
    lv_obj_add_style(button_36, btn_clicked_24, LV_STATE_PRESSED);
    lv_obj_set_style_radius(button_36, 0, 0);
    lv_obj_set_style_bg_opa(button_36, 0, 0);
    lv_obj_set_style_shadow_opa(button_36, 0, 0);
    lv_obj_set_style_pad_right(button_36, 0, 0);
    lv_obj_set_style_pad_bottom(button_36, 0, 0);
    lv_obj_set_style_pad_top(button_36, 0, 0);
    lv_obj_set_ext_click_area(button_36, 30);
    data_binding_add_observer("x_is_homed", button_36, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_observer("x_is_active", button_36, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)background_purple_27 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)background_none_28 } } }, 2, NULL);
    data_binding_add_action(button_36, "set_active_x", 0, NULL, 0, NULL);
    // unnamed: label_37 (label)
    lv_obj_t* label_37 = lv_label_create(button_36);

    lv_label_set_text(label_37, "X");
    lv_obj_center(label_37);


    // unnamed: obj_38 (obj)
    lv_obj_t* obj_38 = lv_obj_create(__name_35);

    lv_obj_add_style(obj_38, flex_y_12, 0);
    lv_obj_add_style(obj_38, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_38, 1, 0);
    lv_obj_set_style_height(obj_38, 1073741823, 0);
    // unnamed: obj_39 (obj)
    lv_obj_t* obj_39 = lv_obj_create(obj_38);

    lv_obj_add_style(obj_39, flex_x_11, 0);
    lv_obj_add_style(obj_39, container_transp_8, 0);
    lv_obj_set_style_size(obj_39, lv_pct(100), 1073741823, 0);
    // unnamed: label_40 (label)
    lv_obj_t* label_40 = lv_label_create(obj_39);

    lv_obj_set_style_text_font(label_40, font_kode_34_1, 0);
    lv_label_set_text(label_40, "000.00 G54");
    lv_obj_set_style_flex_grow(label_40, 1, 0);
    lv_obj_add_style(label_40, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_40, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_x", label_40, 0, "%4.2f", 0, NULL);


    // unnamed: obj_41 (obj)
    lv_obj_t* obj_41 = lv_obj_create(obj_38);

    lv_obj_add_style(obj_41, flex_x_11, 0);
    lv_obj_add_style(obj_41, container_transp_8, 0);
    lv_obj_set_style_size(obj_41, lv_pct(100), 1073741823, 0);
    // unnamed: label_42 (label)
    lv_obj_t* label_42 = lv_label_create(obj_41);

    lv_obj_set_style_text_font(label_42, font_kode_14_5, 0);
    lv_label_set_text(label_42, "000.00");
    lv_obj_set_style_flex_grow(label_42, 1, 0);
    lv_obj_set_style_text_align(label_42, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_42, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_x", label_42, 0, "%4.2f", 0, NULL);

    // unnamed: label_43 (label)
    lv_obj_t* label_43 = lv_label_create(obj_41);

    lv_label_set_text(label_43, "\xef\x84\xa4");
    lv_obj_set_style_width(label_43, 14, 0);

    // unnamed: label_44 (label)
    lv_obj_t* label_44 = lv_label_create(obj_41);

    lv_obj_set_style_text_font(label_44, font_kode_14_5, 0);
    lv_label_set_text(label_44, "000.00   ");
    lv_obj_set_style_text_align(label_44, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_44, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_44, 1, 0);
    data_binding_add_observer("delta_pos_x", label_44, 0, "%4.2f", 0, NULL);

    // unnamed: label_45 (label)
    lv_obj_t* label_45 = lv_label_create(obj_41);

    lv_label_set_text(label_45, "\xef\x81\x91");
    lv_obj_set_style_width(label_45, 14, 0);




    // $name: __name_46 (obj)
    lv_obj_t* __name_46 = lv_obj_create(obj_34);

    obj_registry_add("$name", __name_46);
    lv_obj_add_style(__name_46, flex_x_11, 0);
    lv_obj_add_style(__name_46, container_transp_8, 0);
    lv_obj_add_style(__name_46, bg_group_25, 0);
    lv_obj_set_style_size(__name_46, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_46, 10, 0);
    lv_obj_set_style_pad_bottom(__name_46, 18, 0);
    lv_obj_set_style_border_color(__name_46, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_46, 40, 0);
    lv_obj_set_style_margin_all(__name_46, 2, 0);
    // unnamed: button_47 (button)
    lv_obj_t* button_47 = lv_button_create(__name_46);

    lv_obj_set_style_text_font(button_47, font_kode_40_0, 0);
    lv_obj_set_style_width(button_47, 35, 0);
    lv_obj_add_style(button_47, indicator_light_19, 0);
    lv_obj_add_style(button_47, btn_clicked_24, LV_STATE_PRESSED);
    lv_obj_set_style_radius(button_47, 0, 0);
    lv_obj_set_style_bg_opa(button_47, 0, 0);
    lv_obj_set_style_shadow_opa(button_47, 0, 0);
    lv_obj_set_style_pad_right(button_47, 0, 0);
    lv_obj_set_style_pad_bottom(button_47, 0, 0);
    lv_obj_set_style_pad_top(button_47, 0, 0);
    lv_obj_set_ext_click_area(button_47, 30);
    data_binding_add_observer("y_is_homed", button_47, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_observer("y_is_active", button_47, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)background_purple_27 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)background_none_28 } } }, 2, NULL);
    data_binding_add_action(button_47, "set_active_y", 0, NULL, 0, NULL);
    // unnamed: label_48 (label)
    lv_obj_t* label_48 = lv_label_create(button_47);

    lv_label_set_text(label_48, "Y");
    lv_obj_center(label_48);


    // unnamed: obj_49 (obj)
    lv_obj_t* obj_49 = lv_obj_create(__name_46);

    lv_obj_add_style(obj_49, flex_y_12, 0);
    lv_obj_add_style(obj_49, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_49, 1, 0);
    lv_obj_set_style_height(obj_49, 1073741823, 0);
    // unnamed: obj_50 (obj)
    lv_obj_t* obj_50 = lv_obj_create(obj_49);

    lv_obj_add_style(obj_50, flex_x_11, 0);
    lv_obj_add_style(obj_50, container_transp_8, 0);
    lv_obj_set_style_size(obj_50, lv_pct(100), 1073741823, 0);
    // unnamed: label_51 (label)
    lv_obj_t* label_51 = lv_label_create(obj_50);

    lv_obj_set_style_text_font(label_51, font_kode_34_1, 0);
    lv_label_set_text(label_51, "000.00");
    lv_obj_set_style_flex_grow(label_51, 1, 0);
    lv_obj_add_style(label_51, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_51, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_y", label_51, 0, "%4.2f", 0, NULL);


    // unnamed: obj_52 (obj)
    lv_obj_t* obj_52 = lv_obj_create(obj_49);

    lv_obj_add_style(obj_52, flex_x_11, 0);
    lv_obj_add_style(obj_52, container_transp_8, 0);
    lv_obj_set_style_size(obj_52, lv_pct(100), 1073741823, 0);
    // unnamed: label_53 (label)
    lv_obj_t* label_53 = lv_label_create(obj_52);

    lv_obj_set_style_text_font(label_53, font_kode_14_5, 0);
    lv_label_set_text(label_53, "000.00");
    lv_obj_set_style_flex_grow(label_53, 1, 0);
    lv_obj_set_style_text_align(label_53, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_53, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_y", label_53, 0, "%4.2f", 0, NULL);

    // unnamed: label_54 (label)
    lv_obj_t* label_54 = lv_label_create(obj_52);

    lv_label_set_text(label_54, "\xef\x84\xa4");
    lv_obj_set_style_width(label_54, 14, 0);

    // unnamed: label_55 (label)
    lv_obj_t* label_55 = lv_label_create(obj_52);

    lv_obj_set_style_text_font(label_55, font_kode_14_5, 0);
    lv_label_set_text(label_55, "000.00   ");
    lv_obj_set_style_text_align(label_55, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_55, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_55, 1, 0);
    data_binding_add_observer("delta_pos_y", label_55, 0, "%4.2f", 0, NULL);

    // unnamed: label_56 (label)
    lv_obj_t* label_56 = lv_label_create(obj_52);

    lv_label_set_text(label_56, "\xef\x81\x91");
    lv_obj_set_style_width(label_56, 14, 0);




    // $name: __name_57 (obj)
    lv_obj_t* __name_57 = lv_obj_create(obj_34);

    obj_registry_add("$name", __name_57);
    lv_obj_add_style(__name_57, flex_x_11, 0);
    lv_obj_add_style(__name_57, container_transp_8, 0);
    lv_obj_add_style(__name_57, bg_group_25, 0);
    lv_obj_set_style_size(__name_57, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(__name_57, 10, 0);
    lv_obj_set_style_pad_bottom(__name_57, 18, 0);
    lv_obj_set_style_border_color(__name_57, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_opa(__name_57, 40, 0);
    lv_obj_set_style_margin_all(__name_57, 2, 0);
    // unnamed: button_58 (button)
    lv_obj_t* button_58 = lv_button_create(__name_57);

    lv_obj_set_style_text_font(button_58, font_kode_40_0, 0);
    lv_obj_set_style_width(button_58, 35, 0);
    lv_obj_add_style(button_58, indicator_light_19, 0);
    lv_obj_add_style(button_58, btn_clicked_24, LV_STATE_PRESSED);
    lv_obj_set_style_radius(button_58, 0, 0);
    lv_obj_set_style_bg_opa(button_58, 0, 0);
    lv_obj_set_style_shadow_opa(button_58, 0, 0);
    lv_obj_set_style_pad_right(button_58, 0, 0);
    lv_obj_set_style_pad_bottom(button_58, 0, 0);
    lv_obj_set_style_pad_top(button_58, 0, 0);
    lv_obj_set_ext_click_area(button_58, 30);
    data_binding_add_observer("z_is_homed", button_58, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)indicator_light_green_21 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)indicator_light_red_20 } } }, 2, NULL);
    data_binding_add_observer("z_is_active", button_58, 1, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .p_val = (void*)background_purple_27 } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .p_val = (void*)background_none_28 } } }, 2, NULL);
    data_binding_add_action(button_58, "set_active_z", 0, NULL, 0, NULL);
    // unnamed: label_59 (label)
    lv_obj_t* label_59 = lv_label_create(button_58);

    lv_label_set_text(label_59, "Z");
    lv_obj_center(label_59);


    // unnamed: obj_60 (obj)
    lv_obj_t* obj_60 = lv_obj_create(__name_57);

    lv_obj_add_style(obj_60, flex_y_12, 0);
    lv_obj_add_style(obj_60, container_transp_8, 0);
    lv_obj_set_style_flex_grow(obj_60, 1, 0);
    lv_obj_set_style_height(obj_60, 1073741823, 0);
    // unnamed: obj_61 (obj)
    lv_obj_t* obj_61 = lv_obj_create(obj_60);

    lv_obj_add_style(obj_61, flex_x_11, 0);
    lv_obj_add_style(obj_61, container_transp_8, 0);
    lv_obj_set_style_size(obj_61, lv_pct(100), 1073741823, 0);
    // unnamed: label_62 (label)
    lv_obj_t* label_62 = lv_label_create(obj_61);

    lv_obj_set_style_text_font(label_62, font_kode_34_1, 0);
    lv_label_set_text(label_62, "000.00");
    lv_obj_set_style_flex_grow(label_62, 1, 0);
    lv_obj_add_style(label_62, indicator_green_13, 0);
    lv_obj_set_style_text_align(label_62, LV_TEXT_ALIGN_RIGHT, 0);
    data_binding_add_observer("display_wcs_pos_z", label_62, 0, "%4.2f", 0, NULL);


    // unnamed: obj_63 (obj)
    lv_obj_t* obj_63 = lv_obj_create(obj_60);

    lv_obj_add_style(obj_63, flex_x_11, 0);
    lv_obj_add_style(obj_63, container_transp_8, 0);
    lv_obj_set_style_size(obj_63, lv_pct(100), 1073741823, 0);
    // unnamed: label_64 (label)
    lv_obj_t* label_64 = lv_label_create(obj_63);

    lv_obj_set_style_text_font(label_64, font_kode_14_5, 0);
    lv_label_set_text(label_64, "000.00");
    lv_obj_set_style_flex_grow(label_64, 1, 0);
    lv_obj_set_style_text_align(label_64, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_64, indicator_yellow_14, 0);
    data_binding_add_observer("display_pos_z", label_64, 0, "%4.2f", 0, NULL);

    // unnamed: label_65 (label)
    lv_obj_t* label_65 = lv_label_create(obj_63);

    lv_label_set_text(label_65, "\xef\x84\xa4");
    lv_obj_set_style_width(label_65, 14, 0);

    // unnamed: label_66 (label)
    lv_obj_t* label_66 = lv_label_create(obj_63);

    lv_obj_set_style_text_font(label_66, font_kode_14_5, 0);
    lv_label_set_text(label_66, "000.00   ");
    lv_obj_set_style_text_align(label_66, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_add_style(label_66, indicator_yellow_14, 0);
    lv_obj_set_style_flex_grow(label_66, 1, 0);
    data_binding_add_observer("delta_pos_z", label_66, 0, "%4.2f", 0, NULL);

    // unnamed: label_67 (label)
    lv_obj_t* label_67 = lv_label_create(obj_63);

    lv_label_set_text(label_67, "\xef\x81\x91");
    lv_obj_set_style_width(label_67, 14, 0);




    // unnamed: obj_68 (obj)
    lv_obj_t* obj_68 = lv_obj_create(obj_34);

    lv_obj_set_style_layout(obj_68, LV_LAYOUT_FLEX, 0);
    lv_obj_set_flex_align(obj_68, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_style(obj_68, container_transp_8, 0);
    lv_obj_set_style_size(obj_68, 1073741823, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_68, 5, 0);
    // unnamed: button_69 (button)
    lv_obj_t* button_69 = lv_button_create(obj_68);

    data_binding_add_observer("program_running", button_69, 2, &(bool){NULL}, 0, NULL);
    // unnamed: label_70 (label)
    lv_obj_t* label_70 = lv_label_create(button_69);

    lv_label_set_text(label_70, "\xef\x81\x8b");
    lv_obj_set_style_width(label_70, 1073741823, 0);
    data_binding_add_action(label_70, "program_run", 0, NULL, 0, NULL);


    // unnamed: button_71 (button)
    lv_obj_t* button_71 = lv_button_create(obj_68);

    data_binding_add_observer("program_running", button_71, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = true } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = false } } }, 2, NULL);
    // unnamed: label_72 (label)
    lv_obj_t* label_72 = lv_label_create(button_71);

    lv_label_set_text(label_72, "\xef\x81\x8d");
    lv_obj_set_style_width(label_72, 1073741823, 0);
    data_binding_add_action(label_72, "program_stop", 0, NULL, 0, NULL);


    // unnamed: label_73 (label)
    lv_obj_t* label_73 = lv_label_create(obj_68);

    data_binding_add_observer("machine_mode", label_73, 0, "MODE: %s", 0, NULL);

    // unnamed: label_74 (label)
    lv_obj_t* label_74 = lv_label_create(obj_68);

    lv_obj_add_style(label_74, indicator_yellow_14, 0);
    data_binding_add_observer("wcs_name", label_74, 0, "- %s", 0, NULL);
    data_binding_add_action(label_74, "cycle_wcs", 0, NULL, 0, NULL);




    // unnamed: obj_75 (obj)
    lv_obj_t* obj_75 = lv_obj_create(main_32);

    lv_obj_set_style_layout(obj_75, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_75, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_75, container_7, 0);
    lv_obj_add_style(obj_75, bg_gradient_10, 0);
    lv_obj_set_style_height(obj_75, lv_pct(100), 0);
    lv_obj_set_style_flex_grow(obj_75, 4, 0);
    lv_obj_set_style_pad_top(obj_75, 2, 0);
    lv_obj_set_style_pad_right(obj_75, 2, 0);
    lv_obj_set_style_margin_left(obj_75, 2, 0);
    lv_obj_set_style_margin_right(obj_75, 2, 0);
    // unnamed: obj_76 (obj)
    lv_obj_t* obj_76 = lv_obj_create(obj_75);

    lv_obj_set_style_size(obj_76, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_76, container_transp_8, 0);
    lv_obj_add_style(obj_76, bg_group_25, 0);
    lv_obj_set_style_layout(obj_76, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_76, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_76, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_76, 0, 0);
    lv_obj_set_style_pad_bottom(obj_76, 4, 0);
    lv_obj_set_style_pad_top(obj_76, 4, 0);
    // unnamed: obj_77 (obj)
    lv_obj_t* obj_77 = lv_obj_create(obj_76);

    lv_obj_set_style_layout(obj_77, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_77, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_77, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_77, lv_pct(100), 0);
    lv_obj_set_style_height(obj_77, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_77, 1, 0);
    // unnamed: obj_78 (obj)
    lv_obj_t* obj_78 = lv_obj_create(obj_77);

    lv_obj_set_style_layout(obj_78, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_78, s_static_array_0, s_static_array_1);
    lv_obj_add_style(obj_78, container_transp_8, 0);
    lv_obj_set_style_width(obj_78, lv_pct(100), 0);
    lv_obj_set_style_height(obj_78, 1073741823, 0);
    // unnamed: obj_79 (obj)
    lv_obj_t* obj_79 = lv_obj_create(obj_78);

    lv_obj_set_style_layout(obj_79, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_79, 100, 1073741823, 0);
    lv_obj_add_style(obj_79, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_79, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_79, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_79, 0, 0);
    lv_obj_set_style_pad_bottom(obj_79, -8, 0);
    // unnamed: label_80 (label)
    lv_obj_t* label_80 = lv_label_create(obj_79);

    lv_label_set_text(label_80, "F");
    lv_obj_set_style_text_font(label_80, font_kode_40_0, 0);
    lv_obj_set_style_height(label_80, 1073741823, 0);
    lv_obj_set_style_pad_left(label_80, 5, 0);

    // unnamed: label_81 (label)
    lv_obj_t* label_81 = lv_label_create(obj_79);

    lv_label_set_text(label_81, "FEED");
    lv_obj_set_style_pad_left(label_81, 0, 0);
    lv_obj_set_style_height(label_81, 1073741823, 0);
    lv_obj_set_style_text_font(label_81, font_kode_14_5, 0);
    lv_obj_add_style(label_81, border_top_btn_17, 0);


    // unnamed: label_82 (label)
    lv_obj_t* label_82 = lv_label_create(obj_78);

    lv_obj_set_grid_cell(label_82, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_82, font_kode_30_2, 0);
    lv_obj_set_style_height(label_82, 1073741823, 0);
    lv_label_set_text(label_82, "1000");
    lv_obj_set_style_pad_right(label_82, 5, 0);
    data_binding_add_observer("feed", label_82, 0, "%.0f", 0, NULL);


    // unnamed: obj_83 (obj)
    lv_obj_t* obj_83 = lv_obj_create(obj_77);

    lv_obj_set_style_layout(obj_83, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_83, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_83, container_transp_8, 0);
    lv_obj_set_style_width(obj_83, lv_pct(100), 0);
    lv_obj_set_style_height(obj_83, 1073741823, 0);
    // unnamed: bar_84 (bar)
    lv_obj_t* bar_84 = lv_bar_create(obj_83);

    lv_obj_set_style_width(bar_84, lv_pct(100), 0);
    lv_obj_set_style_height(bar_84, 15, 0);
    lv_obj_set_style_margin_left(bar_84, 15, 0);
    lv_obj_set_style_margin_right(bar_84, 15, 0);
    lv_obj_add_style(bar_84, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_84, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_84, 65, 0);
    lv_bar_set_range(bar_84, 0, 5000);
    lv_obj_set_style_bg_color(bar_84, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_84, 255, 0);
    data_binding_add_observer("feed", bar_84, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_85 (scale)
    lv_obj_t* scale_85 = lv_scale_create(obj_83);

    lv_obj_set_style_width(scale_85, lv_pct(100), 0);
    lv_obj_set_style_height(scale_85, 18, 0);
    lv_obj_set_style_margin_left(scale_85, 15, 0);
    lv_obj_set_style_margin_right(scale_85, 15, 0);
    lv_obj_set_style_margin_bottom(scale_85, 2, 0);
    lv_obj_add_style(scale_85, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_85, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_85, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_86 (obj)
    lv_obj_t* obj_86 = lv_obj_create(obj_76);

    lv_obj_set_style_layout(obj_86, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_86, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_86, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_size(obj_86, 1073741823, 1073741823, 0);
    lv_obj_set_style_min_width(obj_86, 50, 0);
    lv_obj_set_style_pad_right(obj_86, 0, 0);
    lv_obj_set_flex_align(obj_86, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_86, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_pad_top(obj_86, 18, 0);
    data_binding_add_action(obj_86, "set_feed_override", 3, NULL, 0, &(const NumericDialogConfig){ .min_val = 0, .max_val = 200, .initial_val = 100, .format_str = "%d %% ", .text = "Override:" });
    // unnamed: label_87 (label)
    lv_obj_t* label_87 = lv_label_create(obj_86);

    lv_label_set_text(label_87, "MM/MIN");
    lv_obj_set_style_text_font(label_87, font_kode_14_5, 0);
    lv_obj_add_style(label_87, border_top_btn_17, 0);

    // unnamed: label_88 (label)
    lv_obj_t* label_88 = lv_label_create(obj_86);

    lv_label_set_text(label_88, "F Ovr");

    // unnamed: label_89 (label)
    lv_obj_t* label_89 = lv_label_create(obj_86);

    lv_label_set_text(label_89, "65%%");
    lv_obj_set_style_text_font(label_89, font_kode_14_5, 0);
    lv_obj_add_style(label_89, indicator_yellow_14, 0);
    data_binding_add_observer("feed_override_pct", label_89, 0, "%g%%", 0, NULL);



    // unnamed: obj_90 (obj)
    lv_obj_t* obj_90 = lv_obj_create(obj_75);

    lv_obj_set_style_size(obj_90, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_90, container_transp_8, 0);
    lv_obj_add_style(obj_90, bg_group_25, 0);
    lv_obj_set_style_layout(obj_90, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_90, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_90, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_90, 0, 0);
    lv_obj_set_style_pad_bottom(obj_90, 4, 0);
    lv_obj_set_style_pad_top(obj_90, 4, 0);
    // unnamed: obj_91 (obj)
    lv_obj_t* obj_91 = lv_obj_create(obj_90);

    lv_obj_set_style_layout(obj_91, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_91, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_91, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_91, lv_pct(100), 0);
    lv_obj_set_style_height(obj_91, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_91, 1, 0);
    // unnamed: obj_92 (obj)
    lv_obj_t* obj_92 = lv_obj_create(obj_91);

    lv_obj_set_style_layout(obj_92, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_92, s_static_array_2, s_static_array_3);
    lv_obj_add_style(obj_92, container_transp_8, 0);
    lv_obj_set_style_width(obj_92, lv_pct(100), 0);
    lv_obj_set_style_height(obj_92, 1073741823, 0);
    // unnamed: obj_93 (obj)
    lv_obj_t* obj_93 = lv_obj_create(obj_92);

    lv_obj_set_style_layout(obj_93, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_93, 100, 1073741823, 0);
    lv_obj_add_style(obj_93, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_93, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_93, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_93, 0, 0);
    lv_obj_set_style_pad_bottom(obj_93, -8, 0);
    // unnamed: label_94 (label)
    lv_obj_t* label_94 = lv_label_create(obj_93);

    lv_label_set_text(label_94, "S");
    lv_obj_set_style_text_font(label_94, font_kode_40_0, 0);
    lv_obj_set_style_height(label_94, 1073741823, 0);
    lv_obj_set_style_pad_left(label_94, 5, 0);

    // unnamed: label_95 (label)
    lv_obj_t* label_95 = lv_label_create(obj_93);

    lv_label_set_text(label_95, "SPEED");
    lv_obj_set_style_pad_left(label_95, 0, 0);
    lv_obj_set_style_height(label_95, 1073741823, 0);
    lv_obj_set_style_text_font(label_95, font_kode_14_5, 0);
    lv_obj_add_style(label_95, border_top_btn_17, 0);


    // unnamed: label_96 (label)
    lv_obj_t* label_96 = lv_label_create(obj_92);

    lv_obj_set_grid_cell(label_96, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_96, font_kode_30_2, 0);
    lv_obj_set_style_height(label_96, 1073741823, 0);
    lv_label_set_text(label_96, "1000");
    lv_obj_set_style_pad_right(label_96, 5, 0);
    data_binding_add_observer("spindle_rpm", label_96, 0, "%.0f", 0, NULL);


    // unnamed: obj_97 (obj)
    lv_obj_t* obj_97 = lv_obj_create(obj_91);

    lv_obj_set_style_layout(obj_97, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_97, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_97, container_transp_8, 0);
    lv_obj_set_style_width(obj_97, lv_pct(100), 0);
    lv_obj_set_style_height(obj_97, 1073741823, 0);
    // unnamed: bar_98 (bar)
    lv_obj_t* bar_98 = lv_bar_create(obj_97);

    lv_obj_set_style_width(bar_98, lv_pct(100), 0);
    lv_obj_set_style_height(bar_98, 15, 0);
    lv_obj_set_style_margin_left(bar_98, 15, 0);
    lv_obj_set_style_margin_right(bar_98, 15, 0);
    lv_obj_add_style(bar_98, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_98, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_98, 65, 0);
    lv_bar_set_range(bar_98, 0, 24000);
    lv_obj_set_style_bg_color(bar_98, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_98, 255, 0);
    data_binding_add_observer("spindle_rpm", bar_98, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_99 (scale)
    lv_obj_t* scale_99 = lv_scale_create(obj_97);

    lv_obj_set_style_width(scale_99, lv_pct(100), 0);
    lv_obj_set_style_height(scale_99, 18, 0);
    lv_obj_set_style_margin_left(scale_99, 15, 0);
    lv_obj_set_style_margin_right(scale_99, 15, 0);
    lv_obj_set_style_margin_bottom(scale_99, 2, 0);
    lv_obj_add_style(scale_99, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_99, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_99, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_100 (obj)
    lv_obj_t* obj_100 = lv_obj_create(obj_90);

    lv_obj_set_style_layout(obj_100, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_100, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_100, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_size(obj_100, 1073741823, 1073741823, 0);
    lv_obj_set_style_min_width(obj_100, 50, 0);
    lv_obj_set_style_pad_right(obj_100, 0, 0);
    lv_obj_set_flex_align(obj_100, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_100, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_pad_top(obj_100, 18, 0);
    data_binding_add_action(obj_100, "set_speed_override", 3, NULL, 0, &(const NumericDialogConfig){ .min_val = 0, .max_val = 200, .initial_val = 100, .format_str = "%d %% ", .text = "Override:" });
    // unnamed: label_101 (label)
    lv_obj_t* label_101 = lv_label_create(obj_100);

    lv_label_set_text(label_101, "/MIN");
    lv_obj_set_style_text_font(label_101, font_kode_14_5, 0);
    lv_obj_add_style(label_101, border_top_btn_17, 0);

    // unnamed: label_102 (label)
    lv_obj_t* label_102 = lv_label_create(obj_100);

    lv_label_set_text(label_102, "S Ovr");

    // unnamed: label_103 (label)
    lv_obj_t* label_103 = lv_label_create(obj_100);

    lv_label_set_text(label_103, "65%%");
    lv_obj_set_style_text_font(label_103, font_kode_14_5, 0);
    lv_obj_add_style(label_103, indicator_yellow_14, 0);
    data_binding_add_observer("speed_override_pct", label_103, 0, "%g%%", 0, NULL);



    // unnamed: obj_104 (obj)
    lv_obj_t* obj_104 = lv_obj_create(obj_75);

    lv_obj_set_style_size(obj_104, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_104, container_transp_8, 0);
    lv_obj_add_style(obj_104, bg_group_25, 0);
    lv_obj_set_style_layout(obj_104, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_104, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_104, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_104, 0, 0);
    lv_obj_set_style_pad_bottom(obj_104, 18, 0);
    lv_obj_set_style_pad_top(obj_104, 18, 0);
    // unnamed: obj_105 (obj)
    lv_obj_t* obj_105 = lv_obj_create(obj_104);

    lv_obj_set_style_layout(obj_105, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_105, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_105, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_105, lv_pct(100), 0);
    lv_obj_set_style_height(obj_105, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_105, 1, 0);
    // unnamed: label_106 (label)
    lv_obj_t* label_106 = lv_label_create(obj_105);

    lv_label_set_text(label_106, "JOG");
    lv_obj_set_style_height(label_106, 1073741823, 0);
    lv_obj_set_style_width(label_106, lv_pct(100), 0);
    lv_obj_set_style_text_font(label_106, font_kode_20_4, 0);
    lv_obj_add_style(label_106, border_top_btn_17, 0);

    // unnamed: obj_107 (obj)
    lv_obj_t* obj_107 = lv_obj_create(obj_105);

    lv_obj_set_style_layout(obj_107, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_107, s_static_array_4, s_static_array_5);
    lv_obj_add_style(obj_107, container_transp_8, 0);
    lv_obj_set_style_width(obj_107, lv_pct(100), 0);
    lv_obj_set_style_height(obj_107, 1073741823, 0);
    lv_obj_set_style_pad_left(obj_107, 2, 0);
    // unnamed: label_108 (label)
    lv_obj_t* label_108 = lv_label_create(obj_107);

    lv_label_set_text(label_108, "XY");
    lv_obj_set_style_text_font(label_108, font_kode_20_4, 0);
    lv_obj_set_grid_cell(label_108, LV_GRID_ALIGN_START, 0, 1, LV_GRID_ALIGN_START, 0, 1);
    lv_obj_set_style_height(label_108, 1073741823, 0);
    lv_obj_add_flag(label_108, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_108, "cycle_step_xy", 0, NULL, 0, NULL);

    // unnamed: label_109 (label)
    lv_obj_t* label_109 = lv_label_create(obj_107);

    lv_obj_set_grid_cell(label_109, LV_GRID_ALIGN_START, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_109, font_kode_20_4, 0);
    lv_obj_set_style_height(label_109, 1073741823, 0);
    lv_label_set_text(label_109, "10");
    lv_obj_set_style_pad_right(label_109, 10, 0);
    lv_obj_add_style(label_109, indicator_yellow_14, 0);
    lv_obj_add_flag(label_109, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_109, "cycle_step_xy", 0, NULL, 0, NULL);
    data_binding_add_observer("jog_step_xy", label_109, 0, "%g", 0, NULL);

    // unnamed: label_110 (label)
    lv_obj_t* label_110 = lv_label_create(obj_107);

    lv_label_set_text(label_110, "Z");
    lv_obj_set_style_text_font(label_110, font_kode_20_4, 0);
    lv_obj_set_grid_cell(label_110, LV_GRID_ALIGN_START, 2, 1, LV_GRID_ALIGN_START, 0, 1);
    lv_obj_set_style_height(label_110, 1073741823, 0);
    lv_obj_add_flag(label_110, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_110, "cycle_step_z", 0, NULL, 0, NULL);

    // unnamed: label_111 (label)
    lv_obj_t* label_111 = lv_label_create(obj_107);

    lv_obj_set_grid_cell(label_111, LV_GRID_ALIGN_START, 3, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_111, font_kode_20_4, 0);
    lv_obj_set_style_height(label_111, 1073741823, 0);
    lv_label_set_text(label_111, " 5");
    lv_obj_add_style(label_111, indicator_yellow_14, 0);
    lv_obj_add_flag(label_111, LV_OBJ_FLAG_CLICKABLE);
    data_binding_add_action(label_111, "cycle_step_z", 0, NULL, 0, NULL);
    data_binding_add_observer("jog_step_z", label_111, 0, "%g", 0, NULL);



    // unnamed: obj_112 (obj)
    lv_obj_t* obj_112 = lv_obj_create(obj_104);

    lv_obj_set_style_layout(obj_112, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_112, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_112, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_112, 1073741823, 0);
    lv_obj_set_style_min_width(obj_112, 50, 0);
    lv_obj_set_style_height(obj_112, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_112, 0, 0);
    // unnamed: label_113 (label)
    lv_obj_t* label_113 = lv_label_create(obj_112);

    lv_label_set_text(label_113, "MM");
    lv_obj_set_style_text_font(label_113, font_kode_14_5, 0);
    lv_obj_add_style(label_113, border_top_btn_17, 0);

    // unnamed: label_114 (label)
    lv_obj_t* label_114 = lv_label_create(obj_112);

    lv_label_set_text(label_114, "Jog Ovr");

    // unnamed: label_115 (label)
    lv_obj_t* label_115 = lv_label_create(obj_112);

    lv_obj_set_style_text_font(label_115, font_kode_14_5, 0);
    lv_obj_add_style(label_115, indicator_yellow_14, 0);
    lv_label_set_text(label_115, "100% ");


    data_binding_add_observer("program_running", obj_104, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = false } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = true } } }, 2, NULL);

    // unnamed: obj_116 (obj)
    lv_obj_t* obj_116 = lv_obj_create(obj_75);

    lv_obj_set_style_size(obj_116, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(obj_116, container_transp_8, 0);
    lv_obj_add_style(obj_116, bg_group_25, 0);
    lv_obj_set_style_layout(obj_116, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_116, LV_FLEX_FLOW_ROW, 0);
    lv_obj_set_style_height(obj_116, 1073741823, 0);
    lv_obj_set_style_pad_column(obj_116, 0, 0);
    lv_obj_set_style_pad_bottom(obj_116, 4, 0);
    lv_obj_set_style_pad_top(obj_116, 4, 0);
    // unnamed: obj_117 (obj)
    lv_obj_t* obj_117 = lv_obj_create(obj_116);

    lv_obj_set_style_layout(obj_117, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_117, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_117, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_117, lv_pct(100), 0);
    lv_obj_set_style_height(obj_117, 1073741823, 0);
    lv_obj_set_style_flex_grow(obj_117, 1, 0);
    // unnamed: obj_118 (obj)
    lv_obj_t* obj_118 = lv_obj_create(obj_117);

    lv_obj_set_style_layout(obj_118, LV_LAYOUT_GRID, 0);
    lv_obj_set_grid_dsc_array(obj_118, s_static_array_6, s_static_array_7);
    lv_obj_add_style(obj_118, container_transp_8, 0);
    lv_obj_set_style_width(obj_118, lv_pct(100), 0);
    lv_obj_set_style_height(obj_118, 1073741823, 0);
    // unnamed: obj_119 (obj)
    lv_obj_t* obj_119 = lv_obj_create(obj_118);

    lv_obj_set_style_layout(obj_119, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_size(obj_119, 100, 1073741823, 0);
    lv_obj_add_style(obj_119, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_119, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_remove_flag(obj_119, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_column(obj_119, 0, 0);
    lv_obj_set_style_pad_bottom(obj_119, -8, 0);
    // unnamed: label_120 (label)
    lv_obj_t* label_120 = lv_label_create(obj_119);

    lv_label_set_text(label_120, "C");
    lv_obj_set_style_text_font(label_120, font_kode_40_0, 0);
    lv_obj_set_style_height(label_120, 1073741823, 0);
    lv_obj_set_style_pad_left(label_120, 5, 0);

    // unnamed: label_121 (label)
    lv_obj_t* label_121 = lv_label_create(obj_119);

    lv_label_set_text(label_121, "Chipload");
    lv_obj_set_style_pad_left(label_121, 0, 0);
    lv_obj_set_style_height(label_121, 1073741823, 0);
    lv_obj_set_style_text_font(label_121, font_kode_14_5, 0);
    lv_obj_add_style(label_121, border_top_btn_17, 0);


    // unnamed: label_122 (label)
    lv_obj_t* label_122 = lv_label_create(obj_118);

    lv_obj_set_grid_cell(label_122, LV_GRID_ALIGN_END, 1, 1, LV_GRID_ALIGN_END, 0, 1);
    lv_obj_set_style_text_font(label_122, font_kode_30_2, 0);
    lv_obj_set_style_height(label_122, 1073741823, 0);
    lv_label_set_text(label_122, "1000");
    lv_obj_set_style_pad_right(label_122, 5, 0);
    data_binding_add_observer("chipload_disp", label_122, 0, "%.0f", 0, NULL);


    // unnamed: obj_123 (obj)
    lv_obj_t* obj_123 = lv_obj_create(obj_117);

    lv_obj_set_style_layout(obj_123, LV_LAYOUT_FLEX, 0);
    lv_obj_set_style_flex_flow(obj_123, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_add_style(obj_123, container_transp_8, 0);
    lv_obj_set_style_width(obj_123, lv_pct(100), 0);
    lv_obj_set_style_height(obj_123, 1073741823, 0);
    // unnamed: bar_124 (bar)
    lv_obj_t* bar_124 = lv_bar_create(obj_123);

    lv_obj_set_style_width(bar_124, lv_pct(100), 0);
    lv_obj_set_style_height(bar_124, 15, 0);
    lv_obj_set_style_margin_left(bar_124, 15, 0);
    lv_obj_set_style_margin_right(bar_124, 15, 0);
    lv_obj_add_style(bar_124, bar_indicator_9, LV_PART_MAIN);
    lv_obj_add_style(bar_124, bar_indicator_9, LV_PART_INDICATOR);
    lv_bar_set_value(bar_124, 65, 0);
    lv_bar_set_range(bar_124, -50, 150);
    lv_obj_set_style_bg_color(bar_124, lv_color_hex(0x5DD555), 0);
    lv_obj_set_style_bg_opa(bar_124, 255, 0);
    data_binding_add_observer("chipload_disp", bar_124, 5, &(bool){NULL}, 0, NULL);

    // unnamed: scale_125 (scale)
    lv_obj_t* scale_125 = lv_scale_create(obj_123);

    lv_obj_set_style_width(scale_125, lv_pct(100), 0);
    lv_obj_set_style_height(scale_125, 18, 0);
    lv_obj_set_style_margin_left(scale_125, 15, 0);
    lv_obj_set_style_margin_right(scale_125, 15, 0);
    lv_obj_set_style_margin_bottom(scale_125, 2, 0);
    lv_obj_add_style(scale_125, tick_color_26, LV_PART_ITEMS);
    lv_obj_add_style(scale_125, tick_color_26, LV_PART_MAIN);
    lv_obj_add_style(scale_125, tick_color_26, LV_PART_INDICATOR);



    // unnamed: obj_126 (obj)
    lv_obj_t* obj_126 = lv_obj_create(obj_116);

    lv_obj_set_style_layout(obj_126, LV_LAYOUT_FLEX, 0);
    lv_obj_add_style(obj_126, container_transp_8, 0);
    lv_obj_set_style_flex_flow(obj_126, LV_FLEX_FLOW_COLUMN, 0);
    lv_obj_set_style_width(obj_126, 1073741823, 0);
    lv_obj_set_style_min_width(obj_126, 50, 0);
    lv_obj_set_style_height(obj_126, 1073741823, 0);
    lv_obj_set_style_pad_right(obj_126, 0, 0);
    lv_obj_set_style_pad_row(obj_126, 0, 0);
    lv_obj_set_flex_align(obj_126, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(obj_126, LV_OBJ_FLAG_CLICKABLE);
    // unnamed: label_127 (label)
    lv_obj_t* label_127 = lv_label_create(obj_126);

    lv_obj_set_style_text_font(label_127, font_kode_14_5, 0);
    lv_obj_add_style(label_127, indicator_yellow_14, 0);
    data_binding_add_observer("tool_material", label_127, 0, "%s", 0, NULL);

    // unnamed: label_128 (label)
    lv_obj_t* label_128 = lv_label_create(obj_126);

    lv_obj_add_style(label_128, indicator_yellow_14, 0);
    data_binding_add_observer("tool_dia", label_128, 0, "%g mm", 0, NULL);

    // unnamed: label_129 (label)
    lv_obj_t* label_129 = lv_label_create(obj_126);

    lv_obj_set_style_text_font(label_129, font_kode_14_5, 0);
    lv_obj_add_style(label_129, indicator_yellow_14, 0);
    data_binding_add_observer("tool_n_flutes", label_129, 0, "%g-FL", 0, NULL);

    // unnamed: obj_130 (obj)
    lv_obj_t* obj_130 = lv_obj_create(obj_126);

    lv_obj_add_style(obj_130, flex_y_12, 0);
    lv_obj_add_style(obj_130, container_transp_8, 0);
    lv_obj_set_style_size(obj_130, 1073741823, 1073741823, 0);
    lv_obj_set_style_pad_row(obj_130, 0, 0);
    // unnamed: label_131 (label)
    lv_obj_t* label_131 = lv_label_create(obj_130);

    lv_obj_set_style_text_font(label_131, font_kode_14_5, 0);
    data_binding_add_observer("chipload_min", label_131, 0, "%0.2f", 0, NULL);

    // unnamed: label_132 (label)
    lv_obj_t* label_132 = lv_label_create(obj_130);

    lv_obj_set_style_text_font(label_132, font_kode_14_5, 0);
    data_binding_add_observer("chipload_max", label_132, 0, "%0.2f", 0, NULL);



    data_binding_add_observer("program_running", obj_116, 2, (const binding_map_entry_t[]){ { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=true }, .value = { .b_val = true } }, { .key = { .type=BINDING_TYPE_BOOL, .as.b_val=false }, .value = { .b_val = false } } }, 2, NULL);




    // unnamed: obj_133 (obj)
    lv_obj_t* obj_133 = lv_tileview_add_tile(tileview_30, 1, 0, LV_DIR_LEFT);

    lv_obj_add_style(obj_133, container_7, 0);
    // unnamed: obj_134 (obj)
    lv_obj_t* obj_134 = lv_obj_create(obj_133);

    lv_obj_add_style(obj_134, container_transp_8, 0);
    lv_obj_add_style(obj_134, flex_x_11, 0);
    lv_obj_set_style_size(obj_134, lv_pct(100), lv_pct(100), 0);
    // unnamed: tabview_135 (tabview)
    lv_obj_t* tabview_135 = lv_tabview_create(obj_134);

    lv_tabview_set_tab_bar_position(tabview_135, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(tabview_135, 40);
    lv_obj_set_style_size(tabview_135, 500, lv_pct(100), 0);
    lv_obj_add_style(tabview_135, container_transp_8, 0);
    lv_obj_add_style(tabview_135, bg_gradient_10, 0);
    // unnamed: obj_136 (obj)
    lv_obj_t* obj_136 = lv_tabview_get_tab_bar(tabview_135);

    lv_obj_add_style(obj_136, container_transp_8, 0);
    lv_obj_add_style(obj_136, bg_gradient_10, 0);

    // unnamed: obj_137 (obj)
    lv_obj_t* obj_137 = lv_tabview_get_content(tabview_135);

    lv_obj_remove_flag(obj_137, LV_OBJ_FLAG_SCROLLABLE);

    // unnamed: obj_138 (obj)
    lv_obj_t* obj_138 = lv_tabview_add_tab(tabview_135, "Modes");

    lv_obj_add_style(obj_138, container_transp_8, 0);
    lv_obj_set_style_size(obj_138, 1073741823, 1073741823, 0);
    lv_obj_remove_flag(obj_138, LV_OBJ_FLAG_SCROLLABLE);
    // unnamed: obj_139 (obj)
    lv_obj_t* obj_139 = lv_obj_create(obj_138);

    lv_obj_add_style(obj_139, container_transp_8, 0);
    lv_obj_add_style(obj_139, bg_gradient_10, 0);
    lv_obj_set_style_size(obj_139, 1073741823, 1073741823, 0);
    // unnamed: obj_140 (obj)
    lv_obj_t* obj_140 = lv_obj_create(obj_139);

    lv_obj_set_style_layout(obj_140, LV_LAYOUT_GRID, 0);
    lv_obj_set_style_size(obj_140, 1073741823, 1073741823, 0);
    lv_obj_add_style(obj_140, container_transp_8, 0);
    lv_obj_add_style(obj_140, bg_group_25, 0);
    lv_obj_set_style_pad_all(obj_140, 10, 0);
    lv_obj_set_grid_dsc_array(obj_140, s_static_array_8, s_static_array_9);
    // unnamed: obj_141 (obj)
    lv_obj_t* obj_141 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_141, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_141, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_141, 150, 150, 0);
    // unnamed: button_142 (button)
    lv_obj_t* button_142 = lv_button_create(obj_141);

    lv_obj_set_style_size(button_142, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_142, container_transp_8, 0);
    lv_obj_set_style_border_width(button_142, 0, 0);
    lv_obj_set_style_outline_width(button_142, 0, 0);
    lv_obj_set_style_shadow_width(button_142, 5, 0);
    lv_obj_set_style_shadow_opa(button_142, 100, 0);
    lv_obj_set_style_shadow_spread(button_142, 3, 0);
    lv_obj_set_style_pad_all(button_142, 5, 0);
    // unnamed: image_143 (image)
    lv_obj_t* image_143 = lv_image_create(button_142);

    lv_image_set_src(image_143, &img_probe_icon_0);



    // unnamed: obj_144 (obj)
    lv_obj_t* obj_144 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_144, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_144, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_144, 150, 150, 0);
    // unnamed: button_145 (button)
    lv_obj_t* button_145 = lv_button_create(obj_144);

    lv_obj_set_style_size(button_145, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_145, container_transp_8, 0);
    lv_obj_set_style_border_width(button_145, 0, 0);
    lv_obj_set_style_outline_width(button_145, 0, 0);
    lv_obj_set_style_shadow_width(button_145, 5, 0);
    lv_obj_set_style_shadow_opa(button_145, 100, 0);
    lv_obj_set_style_shadow_spread(button_145, 3, 0);
    lv_obj_set_style_pad_all(button_145, 5, 0);
    // unnamed: image_146 (image)
    lv_obj_t* image_146 = lv_image_create(button_145);

    lv_image_set_src(image_146, &img_probe_icon_1);



    // unnamed: obj_147 (obj)
    lv_obj_t* obj_147 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_147, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_147, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_147, 150, 150, 0);
    // unnamed: button_148 (button)
    lv_obj_t* button_148 = lv_button_create(obj_147);

    lv_obj_set_style_size(button_148, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_148, container_transp_8, 0);
    lv_obj_set_style_border_width(button_148, 0, 0);
    lv_obj_set_style_outline_width(button_148, 0, 0);
    lv_obj_set_style_shadow_width(button_148, 5, 0);
    lv_obj_set_style_shadow_opa(button_148, 100, 0);
    lv_obj_set_style_shadow_spread(button_148, 3, 0);
    lv_obj_set_style_pad_all(button_148, 5, 0);
    // unnamed: image_149 (image)
    lv_obj_t* image_149 = lv_image_create(button_148);

    lv_image_set_src(image_149, &img_probe_icon_2);



    // unnamed: obj_150 (obj)
    lv_obj_t* obj_150 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_150, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_150, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_150, 150, 150, 0);
    // unnamed: button_151 (button)
    lv_obj_t* button_151 = lv_button_create(obj_150);

    lv_obj_set_style_size(button_151, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_151, container_transp_8, 0);
    lv_obj_set_style_border_width(button_151, 0, 0);
    lv_obj_set_style_outline_width(button_151, 0, 0);
    lv_obj_set_style_shadow_width(button_151, 5, 0);
    lv_obj_set_style_shadow_opa(button_151, 100, 0);
    lv_obj_set_style_shadow_spread(button_151, 3, 0);
    lv_obj_set_style_pad_all(button_151, 5, 0);
    // unnamed: image_152 (image)
    lv_obj_t* image_152 = lv_image_create(button_151);

    lv_image_set_src(image_152, &img_probe_icon_3);



    // unnamed: obj_153 (obj)
    lv_obj_t* obj_153 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_153, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_153, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_153, 150, 150, 0);
    // unnamed: button_154 (button)
    lv_obj_t* button_154 = lv_button_create(obj_153);

    lv_obj_set_style_size(button_154, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_154, container_transp_8, 0);
    lv_obj_set_style_border_width(button_154, 0, 0);
    lv_obj_set_style_outline_width(button_154, 0, 0);
    lv_obj_set_style_shadow_width(button_154, 5, 0);
    lv_obj_set_style_shadow_opa(button_154, 100, 0);
    lv_obj_set_style_shadow_spread(button_154, 3, 0);
    lv_obj_set_style_pad_all(button_154, 5, 0);
    // unnamed: image_155 (image)
    lv_obj_t* image_155 = lv_image_create(button_154);

    lv_image_set_src(image_155, &img_probe_icon_4);



    // unnamed: obj_156 (obj)
    lv_obj_t* obj_156 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_156, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_156, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_156, 150, 150, 0);
    // unnamed: button_157 (button)
    lv_obj_t* button_157 = lv_button_create(obj_156);

    lv_obj_set_style_size(button_157, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_157, container_transp_8, 0);
    lv_obj_set_style_border_width(button_157, 0, 0);
    lv_obj_set_style_outline_width(button_157, 0, 0);
    lv_obj_set_style_shadow_width(button_157, 5, 0);
    lv_obj_set_style_shadow_opa(button_157, 100, 0);
    lv_obj_set_style_shadow_spread(button_157, 3, 0);
    lv_obj_set_style_pad_all(button_157, 5, 0);
    // unnamed: image_158 (image)
    lv_obj_t* image_158 = lv_image_create(button_157);

    lv_image_set_src(image_158, &img_probe_icon_5);



    // unnamed: obj_159 (obj)
    lv_obj_t* obj_159 = lv_obj_create(obj_140);

    lv_obj_add_style(obj_159, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_159, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_159, 150, 150, 0);
    // unnamed: button_160 (button)
    lv_obj_t* button_160 = lv_button_create(obj_159);

    lv_obj_set_style_size(button_160, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_160, container_transp_8, 0);
    lv_obj_set_style_border_width(button_160, 0, 0);
    lv_obj_set_style_outline_width(button_160, 0, 0);
    lv_obj_set_style_shadow_width(button_160, 5, 0);
    lv_obj_set_style_shadow_opa(button_160, 100, 0);
    lv_obj_set_style_shadow_spread(button_160, 3, 0);
    lv_obj_set_style_pad_all(button_160, 5, 0);
    // unnamed: image_161 (image)
    lv_obj_t* image_161 = lv_image_create(button_160);

    lv_image_set_src(image_161, &img_probe_icon_6);






    // unnamed: obj_162 (obj)
    lv_obj_t* obj_162 = lv_tabview_add_tab(tabview_135, "Inside");

    lv_obj_add_style(obj_162, container_transp_8, 0);
    lv_obj_set_style_size(obj_162, 1073741823, 1073741823, 0);
    lv_obj_remove_flag(obj_162, LV_OBJ_FLAG_SCROLLABLE);
    // unnamed: obj_163 (obj)
    lv_obj_t* obj_163 = lv_obj_create(obj_162);

    lv_obj_add_style(obj_163, container_transp_8, 0);
    lv_obj_add_style(obj_163, bg_gradient_10, 0);
    lv_obj_set_style_size(obj_163, 1073741823, 1073741823, 0);
    // unnamed: obj_164 (obj)
    lv_obj_t* obj_164 = lv_obj_create(obj_163);

    lv_obj_set_style_layout(obj_164, LV_LAYOUT_GRID, 0);
    lv_obj_set_style_size(obj_164, 1073741823, 1073741823, 0);
    lv_obj_add_style(obj_164, container_transp_8, 0);
    lv_obj_add_style(obj_164, bg_group_25, 0);
    lv_obj_set_style_pad_all(obj_164, 10, 0);
    lv_obj_set_grid_dsc_array(obj_164, s_static_array_10, s_static_array_11);
    // unnamed: obj_165 (obj)
    lv_obj_t* obj_165 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_165, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_165, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_165, 150, 150, 0);
    // unnamed: button_166 (button)
    lv_obj_t* button_166 = lv_button_create(obj_165);

    lv_obj_set_style_size(button_166, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_166, container_transp_8, 0);
    lv_obj_set_style_border_width(button_166, 0, 0);
    lv_obj_set_style_outline_width(button_166, 0, 0);
    lv_obj_set_style_shadow_width(button_166, 5, 0);
    lv_obj_set_style_shadow_opa(button_166, 100, 0);
    lv_obj_set_style_shadow_spread(button_166, 3, 0);
    lv_obj_set_style_pad_all(button_166, 5, 0);
    // unnamed: image_167 (image)
    lv_obj_t* image_167 = lv_image_create(button_166);

    lv_image_set_src(image_167, &img_probe_grid_0);



    // unnamed: obj_168 (obj)
    lv_obj_t* obj_168 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_168, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_168, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_168, 150, 150, 0);
    // unnamed: button_169 (button)
    lv_obj_t* button_169 = lv_button_create(obj_168);

    lv_obj_set_style_size(button_169, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_169, container_transp_8, 0);
    lv_obj_set_style_border_width(button_169, 0, 0);
    lv_obj_set_style_outline_width(button_169, 0, 0);
    lv_obj_set_style_shadow_width(button_169, 5, 0);
    lv_obj_set_style_shadow_opa(button_169, 100, 0);
    lv_obj_set_style_shadow_spread(button_169, 3, 0);
    lv_obj_set_style_pad_all(button_169, 5, 0);
    // unnamed: image_170 (image)
    lv_obj_t* image_170 = lv_image_create(button_169);

    lv_image_set_src(image_170, &img_probe_grid_1);



    // unnamed: obj_171 (obj)
    lv_obj_t* obj_171 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_171, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_171, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_171, 150, 150, 0);
    // unnamed: button_172 (button)
    lv_obj_t* button_172 = lv_button_create(obj_171);

    lv_obj_set_style_size(button_172, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_172, container_transp_8, 0);
    lv_obj_set_style_border_width(button_172, 0, 0);
    lv_obj_set_style_outline_width(button_172, 0, 0);
    lv_obj_set_style_shadow_width(button_172, 5, 0);
    lv_obj_set_style_shadow_opa(button_172, 100, 0);
    lv_obj_set_style_shadow_spread(button_172, 3, 0);
    lv_obj_set_style_pad_all(button_172, 5, 0);
    // unnamed: image_173 (image)
    lv_obj_t* image_173 = lv_image_create(button_172);

    lv_image_set_src(image_173, &img_probe_grid_2);



    // unnamed: obj_174 (obj)
    lv_obj_t* obj_174 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_174, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_174, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_174, 150, 150, 0);
    // unnamed: button_175 (button)
    lv_obj_t* button_175 = lv_button_create(obj_174);

    lv_obj_set_style_size(button_175, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_175, container_transp_8, 0);
    lv_obj_set_style_border_width(button_175, 0, 0);
    lv_obj_set_style_outline_width(button_175, 0, 0);
    lv_obj_set_style_shadow_width(button_175, 5, 0);
    lv_obj_set_style_shadow_opa(button_175, 100, 0);
    lv_obj_set_style_shadow_spread(button_175, 3, 0);
    lv_obj_set_style_pad_all(button_175, 5, 0);
    // unnamed: image_176 (image)
    lv_obj_t* image_176 = lv_image_create(button_175);

    lv_image_set_src(image_176, &img_probe_grid_3);



    // unnamed: obj_177 (obj)
    lv_obj_t* obj_177 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_177, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_177, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_177, 150, 150, 0);
    // unnamed: button_178 (button)
    lv_obj_t* button_178 = lv_button_create(obj_177);

    lv_obj_set_style_size(button_178, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_178, container_transp_8, 0);
    lv_obj_set_style_border_width(button_178, 0, 0);
    lv_obj_set_style_outline_width(button_178, 0, 0);
    lv_obj_set_style_shadow_width(button_178, 5, 0);
    lv_obj_set_style_shadow_opa(button_178, 100, 0);
    lv_obj_set_style_shadow_spread(button_178, 3, 0);
    lv_obj_set_style_pad_all(button_178, 5, 0);
    // unnamed: image_179 (image)
    lv_obj_t* image_179 = lv_image_create(button_178);

    lv_image_set_src(image_179, &img_probe_grid_4);



    // unnamed: obj_180 (obj)
    lv_obj_t* obj_180 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_180, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_180, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_180, 150, 150, 0);
    // unnamed: button_181 (button)
    lv_obj_t* button_181 = lv_button_create(obj_180);

    lv_obj_set_style_size(button_181, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_181, container_transp_8, 0);
    lv_obj_set_style_border_width(button_181, 0, 0);
    lv_obj_set_style_outline_width(button_181, 0, 0);
    lv_obj_set_style_shadow_width(button_181, 5, 0);
    lv_obj_set_style_shadow_opa(button_181, 100, 0);
    lv_obj_set_style_shadow_spread(button_181, 3, 0);
    lv_obj_set_style_pad_all(button_181, 5, 0);
    // unnamed: image_182 (image)
    lv_obj_t* image_182 = lv_image_create(button_181);

    lv_image_set_src(image_182, &img_probe_grid_5);



    // unnamed: obj_183 (obj)
    lv_obj_t* obj_183 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_183, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_183, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_183, 150, 150, 0);
    // unnamed: button_184 (button)
    lv_obj_t* button_184 = lv_button_create(obj_183);

    lv_obj_set_style_size(button_184, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_184, container_transp_8, 0);
    lv_obj_set_style_border_width(button_184, 0, 0);
    lv_obj_set_style_outline_width(button_184, 0, 0);
    lv_obj_set_style_shadow_width(button_184, 5, 0);
    lv_obj_set_style_shadow_opa(button_184, 100, 0);
    lv_obj_set_style_shadow_spread(button_184, 3, 0);
    lv_obj_set_style_pad_all(button_184, 5, 0);
    // unnamed: image_185 (image)
    lv_obj_t* image_185 = lv_image_create(button_184);

    lv_image_set_src(image_185, &img_probe_grid_6);



    // unnamed: obj_186 (obj)
    lv_obj_t* obj_186 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_186, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_186, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_186, 150, 150, 0);
    // unnamed: button_187 (button)
    lv_obj_t* button_187 = lv_button_create(obj_186);

    lv_obj_set_style_size(button_187, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_187, container_transp_8, 0);
    lv_obj_set_style_border_width(button_187, 0, 0);
    lv_obj_set_style_outline_width(button_187, 0, 0);
    lv_obj_set_style_shadow_width(button_187, 5, 0);
    lv_obj_set_style_shadow_opa(button_187, 100, 0);
    lv_obj_set_style_shadow_spread(button_187, 3, 0);
    lv_obj_set_style_pad_all(button_187, 5, 0);
    // unnamed: image_188 (image)
    lv_obj_t* image_188 = lv_image_create(button_187);

    lv_image_set_src(image_188, &img_probe_grid_7);



    // unnamed: obj_189 (obj)
    lv_obj_t* obj_189 = lv_obj_create(obj_164);

    lv_obj_add_style(obj_189, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_189, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_189, 150, 150, 0);
    // unnamed: button_190 (button)
    lv_obj_t* button_190 = lv_button_create(obj_189);

    lv_obj_set_style_size(button_190, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_190, container_transp_8, 0);
    lv_obj_set_style_border_width(button_190, 0, 0);
    lv_obj_set_style_outline_width(button_190, 0, 0);
    lv_obj_set_style_shadow_width(button_190, 5, 0);
    lv_obj_set_style_shadow_opa(button_190, 100, 0);
    lv_obj_set_style_shadow_spread(button_190, 3, 0);
    lv_obj_set_style_pad_all(button_190, 5, 0);
    // unnamed: image_191 (image)
    lv_obj_t* image_191 = lv_image_create(button_190);

    lv_image_set_src(image_191, &img_probe_grid_8);






    // unnamed: obj_192 (obj)
    lv_obj_t* obj_192 = lv_tabview_add_tab(tabview_135, "Outside");

    lv_obj_add_style(obj_192, container_transp_8, 0);
    lv_obj_set_style_size(obj_192, 1073741823, 1073741823, 0);
    // unnamed: obj_193 (obj)
    lv_obj_t* obj_193 = lv_obj_create(obj_192);

    lv_obj_add_style(obj_193, container_transp_8, 0);
    lv_obj_add_style(obj_193, bg_gradient_10, 0);
    lv_obj_set_style_size(obj_193, 1073741823, 1073741823, 0);
    // unnamed: obj_194 (obj)
    lv_obj_t* obj_194 = lv_obj_create(obj_193);

    lv_obj_set_style_layout(obj_194, LV_LAYOUT_GRID, 0);
    lv_obj_set_style_size(obj_194, 1073741823, 1073741823, 0);
    lv_obj_add_style(obj_194, container_transp_8, 0);
    lv_obj_add_style(obj_194, bg_group_25, 0);
    lv_obj_set_style_pad_all(obj_194, 10, 0);
    lv_obj_set_grid_dsc_array(obj_194, s_static_array_12, s_static_array_13);
    // unnamed: obj_195 (obj)
    lv_obj_t* obj_195 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_195, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_195, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_195, 150, 150, 0);
    // unnamed: button_196 (button)
    lv_obj_t* button_196 = lv_button_create(obj_195);

    lv_obj_set_style_size(button_196, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_196, container_transp_8, 0);
    lv_obj_set_style_border_width(button_196, 0, 0);
    lv_obj_set_style_outline_width(button_196, 0, 0);
    lv_obj_set_style_shadow_width(button_196, 5, 0);
    lv_obj_set_style_shadow_opa(button_196, 100, 0);
    lv_obj_set_style_shadow_spread(button_196, 3, 0);
    lv_obj_set_style_pad_all(button_196, 5, 0);
    // unnamed: image_197 (image)
    lv_obj_t* image_197 = lv_image_create(button_196);

    lv_image_set_src(image_197, &img_probe_out_0);



    // unnamed: obj_198 (obj)
    lv_obj_t* obj_198 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_198, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_198, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_198, 150, 150, 0);
    // unnamed: button_199 (button)
    lv_obj_t* button_199 = lv_button_create(obj_198);

    lv_obj_set_style_size(button_199, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_199, container_transp_8, 0);
    lv_obj_set_style_border_width(button_199, 0, 0);
    lv_obj_set_style_outline_width(button_199, 0, 0);
    lv_obj_set_style_shadow_width(button_199, 5, 0);
    lv_obj_set_style_shadow_opa(button_199, 100, 0);
    lv_obj_set_style_shadow_spread(button_199, 3, 0);
    lv_obj_set_style_pad_all(button_199, 5, 0);
    // unnamed: image_200 (image)
    lv_obj_t* image_200 = lv_image_create(button_199);

    lv_image_set_src(image_200, &img_probe_out_1);



    // unnamed: obj_201 (obj)
    lv_obj_t* obj_201 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_201, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_201, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_style_size(obj_201, 150, 150, 0);
    // unnamed: button_202 (button)
    lv_obj_t* button_202 = lv_button_create(obj_201);

    lv_obj_set_style_size(button_202, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_202, container_transp_8, 0);
    lv_obj_set_style_border_width(button_202, 0, 0);
    lv_obj_set_style_outline_width(button_202, 0, 0);
    lv_obj_set_style_shadow_width(button_202, 5, 0);
    lv_obj_set_style_shadow_opa(button_202, 100, 0);
    lv_obj_set_style_shadow_spread(button_202, 3, 0);
    lv_obj_set_style_pad_all(button_202, 5, 0);
    // unnamed: image_203 (image)
    lv_obj_t* image_203 = lv_image_create(button_202);

    lv_image_set_src(image_203, &img_probe_out_2);



    // unnamed: obj_204 (obj)
    lv_obj_t* obj_204 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_204, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_204, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_204, 150, 150, 0);
    // unnamed: button_205 (button)
    lv_obj_t* button_205 = lv_button_create(obj_204);

    lv_obj_set_style_size(button_205, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_205, container_transp_8, 0);
    lv_obj_set_style_border_width(button_205, 0, 0);
    lv_obj_set_style_outline_width(button_205, 0, 0);
    lv_obj_set_style_shadow_width(button_205, 5, 0);
    lv_obj_set_style_shadow_opa(button_205, 100, 0);
    lv_obj_set_style_shadow_spread(button_205, 3, 0);
    lv_obj_set_style_pad_all(button_205, 5, 0);
    // unnamed: image_206 (image)
    lv_obj_t* image_206 = lv_image_create(button_205);

    lv_image_set_src(image_206, &img_probe_out_3);



    // unnamed: obj_207 (obj)
    lv_obj_t* obj_207 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_207, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_207, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_207, 150, 150, 0);
    // unnamed: button_208 (button)
    lv_obj_t* button_208 = lv_button_create(obj_207);

    lv_obj_set_style_size(button_208, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_208, container_transp_8, 0);
    lv_obj_set_style_border_width(button_208, 0, 0);
    lv_obj_set_style_outline_width(button_208, 0, 0);
    lv_obj_set_style_shadow_width(button_208, 5, 0);
    lv_obj_set_style_shadow_opa(button_208, 100, 0);
    lv_obj_set_style_shadow_spread(button_208, 3, 0);
    lv_obj_set_style_pad_all(button_208, 5, 0);
    // unnamed: image_209 (image)
    lv_obj_t* image_209 = lv_image_create(button_208);

    lv_image_set_src(image_209, &img_probe_out_4);



    // unnamed: obj_210 (obj)
    lv_obj_t* obj_210 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_210, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_210, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_style_size(obj_210, 150, 150, 0);
    // unnamed: button_211 (button)
    lv_obj_t* button_211 = lv_button_create(obj_210);

    lv_obj_set_style_size(button_211, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_211, container_transp_8, 0);
    lv_obj_set_style_border_width(button_211, 0, 0);
    lv_obj_set_style_outline_width(button_211, 0, 0);
    lv_obj_set_style_shadow_width(button_211, 5, 0);
    lv_obj_set_style_shadow_opa(button_211, 100, 0);
    lv_obj_set_style_shadow_spread(button_211, 3, 0);
    lv_obj_set_style_pad_all(button_211, 5, 0);
    // unnamed: image_212 (image)
    lv_obj_t* image_212 = lv_image_create(button_211);

    lv_image_set_src(image_212, &img_probe_out_5);



    // unnamed: obj_213 (obj)
    lv_obj_t* obj_213 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_213, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_213, LV_GRID_ALIGN_CENTER, 0, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_213, 150, 150, 0);
    // unnamed: button_214 (button)
    lv_obj_t* button_214 = lv_button_create(obj_213);

    lv_obj_set_style_size(button_214, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_214, container_transp_8, 0);
    lv_obj_set_style_border_width(button_214, 0, 0);
    lv_obj_set_style_outline_width(button_214, 0, 0);
    lv_obj_set_style_shadow_width(button_214, 5, 0);
    lv_obj_set_style_shadow_opa(button_214, 100, 0);
    lv_obj_set_style_shadow_spread(button_214, 3, 0);
    lv_obj_set_style_pad_all(button_214, 5, 0);
    // unnamed: image_215 (image)
    lv_obj_t* image_215 = lv_image_create(button_214);

    lv_image_set_src(image_215, &img_probe_out_6);



    // unnamed: obj_216 (obj)
    lv_obj_t* obj_216 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_216, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_216, LV_GRID_ALIGN_CENTER, 1, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_216, 150, 150, 0);
    // unnamed: button_217 (button)
    lv_obj_t* button_217 = lv_button_create(obj_216);

    lv_obj_set_style_size(button_217, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_217, container_transp_8, 0);
    lv_obj_set_style_border_width(button_217, 0, 0);
    lv_obj_set_style_outline_width(button_217, 0, 0);
    lv_obj_set_style_shadow_width(button_217, 5, 0);
    lv_obj_set_style_shadow_opa(button_217, 100, 0);
    lv_obj_set_style_shadow_spread(button_217, 3, 0);
    lv_obj_set_style_pad_all(button_217, 5, 0);
    // unnamed: image_218 (image)
    lv_obj_t* image_218 = lv_image_create(button_217);

    lv_image_set_src(image_218, &img_probe_out_7);



    // unnamed: obj_219 (obj)
    lv_obj_t* obj_219 = lv_obj_create(obj_194);

    lv_obj_add_style(obj_219, container_transp_8, 0);
    lv_obj_set_grid_cell(obj_219, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_style_size(obj_219, 150, 150, 0);
    // unnamed: button_220 (button)
    lv_obj_t* button_220 = lv_button_create(obj_219);

    lv_obj_set_style_size(button_220, lv_pct(100), lv_pct(100), 0);
    lv_obj_add_style(button_220, container_transp_8, 0);
    lv_obj_set_style_border_width(button_220, 0, 0);
    lv_obj_set_style_outline_width(button_220, 0, 0);
    lv_obj_set_style_shadow_width(button_220, 5, 0);
    lv_obj_set_style_shadow_opa(button_220, 100, 0);
    lv_obj_set_style_shadow_spread(button_220, 3, 0);
    lv_obj_set_style_pad_all(button_220, 5, 0);
    // unnamed: image_221 (image)
    lv_obj_t* image_221 = lv_image_create(button_220);

    lv_image_set_src(image_221, &img_probe_out_8);






    // unnamed: obj_222 (obj)
    lv_obj_t* obj_222 = lv_tabview_add_tab(tabview_135, "Misc");


    // unnamed: obj_223 (obj)
    lv_obj_t* obj_223 = lv_obj_create(obj_134);

    lv_obj_add_style(obj_223, container_transp_8, 0);
    lv_obj_add_style(obj_223, bg_gradient_10, 0);
    lv_obj_add_style(obj_223, flex_y_12, 0);
    lv_obj_set_style_size(obj_223, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_row(obj_223, 8, 0);
    lv_obj_set_style_pad_all(obj_223, 10, 0);
    lv_obj_set_style_flex_grow(obj_223, 1, 0);
    // unnamed: obj_224 (obj)
    lv_obj_t* obj_224 = lv_obj_create(obj_223);

    lv_obj_add_style(obj_224, container_transp_8, 0);
    lv_obj_add_style(obj_224, flex_x_11, 0);
    lv_obj_add_style(obj_224, bg_group_25, 0);
    lv_obj_set_style_size(obj_224, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_224, 3, 0);
    // unnamed: label_225 (label)
    lv_obj_t* label_225 = lv_label_create(obj_224);

    lv_obj_set_style_flex_grow(label_225, 5, 0);
    lv_label_set_text(label_225, "Width / Radius:");

    // unnamed: label_226 (label)
    lv_obj_t* label_226 = lv_label_create(obj_224);

    lv_obj_add_style(label_226, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_226, 2, 0);
    lv_label_set_text(label_226, "100 mm");
    data_binding_add_observer("probe_w", label_226, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_226, "set_probe_width", 3, NULL, 0, &(const NumericDialogConfig){ .format_str = "%d mm", .min_val = 1, .max_val = 200, .initial_val = 100, .text = "Width / Radius:" });


    // unnamed: obj_227 (obj)
    lv_obj_t* obj_227 = lv_obj_create(obj_223);

    lv_obj_add_style(obj_227, container_transp_8, 0);
    lv_obj_add_style(obj_227, flex_x_11, 0);
    lv_obj_add_style(obj_227, bg_group_25, 0);
    lv_obj_set_style_size(obj_227, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_227, 3, 0);
    // unnamed: label_228 (label)
    lv_obj_t* label_228 = lv_label_create(obj_227);

    lv_obj_set_style_flex_grow(label_228, 5, 0);
    lv_label_set_text(label_228, "Height:");

    // unnamed: label_229 (label)
    lv_obj_t* label_229 = lv_label_create(obj_227);

    lv_obj_add_style(label_229, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_229, 2, 0);
    lv_label_set_text(label_229, "100 mm");
    data_binding_add_observer("probe_h", label_229, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_229, "set_probe_height", 3, NULL, 0, &(const NumericDialogConfig){ .format_str = "%d mm", .min_val = 1, .max_val = 200, .initial_val = 100, .text = "Height:" });


    // unnamed: obj_230 (obj)
    lv_obj_t* obj_230 = lv_obj_create(obj_223);

    lv_obj_add_style(obj_230, container_transp_8, 0);
    lv_obj_add_style(obj_230, flex_x_11, 0);
    lv_obj_add_style(obj_230, bg_group_25, 0);
    lv_obj_set_style_size(obj_230, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_230, 3, 0);
    // unnamed: label_231 (label)
    lv_obj_t* label_231 = lv_label_create(obj_230);

    lv_obj_set_style_flex_grow(label_231, 5, 0);
    lv_label_set_text(label_231, "Clearance:");

    // unnamed: label_232 (label)
    lv_obj_t* label_232 = lv_label_create(obj_230);

    lv_obj_add_style(label_232, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_232, 2, 0);
    lv_label_set_text(label_232, "5 mm");
    data_binding_add_observer("probe_cl", label_232, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_232, "set_probe_cl", 3, NULL, 0, &(const NumericDialogConfig){ .format_str = "%d mm", .min_val = 1, .max_val = 20, .initial_val = 5, .text = "Clearance:" });


    // unnamed: obj_233 (obj)
    lv_obj_t* obj_233 = lv_obj_create(obj_223);

    lv_obj_add_style(obj_233, container_transp_8, 0);
    lv_obj_add_style(obj_233, flex_x_11, 0);
    lv_obj_add_style(obj_233, bg_group_25, 0);
    lv_obj_set_style_size(obj_233, lv_pct(100), 1073741823, 0);
    lv_obj_set_style_pad_all(obj_233, 3, 0);
    // unnamed: label_234 (label)
    lv_obj_t* label_234 = lv_label_create(obj_233);

    lv_obj_set_style_flex_grow(label_234, 5, 0);
    lv_label_set_text(label_234, "Overtravel:");

    // unnamed: label_235 (label)
    lv_obj_t* label_235 = lv_label_create(obj_233);

    lv_obj_add_style(label_235, text_actionable_15, 0);
    lv_obj_set_style_flex_grow(label_235, 2, 0);
    lv_label_set_text(label_235, "2 mm");
    data_binding_add_observer("probe_ov", label_235, 0, "%g mm", 0, NULL);
    data_binding_add_action(label_235, "set_probe_ov", 3, NULL, 0, &(const NumericDialogConfig){ .format_str = "%d mm", .min_val = 0.1, .max_val = 10, .initial_val = 2, .text = "Overtravel:" });


    // unnamed: obj_236 (obj)
    lv_obj_t* obj_236 = lv_obj_create(obj_223);

    lv_obj_add_style(obj_236, container_transp_8, 0);
    lv_obj_add_style(obj_236, flex_x_11, 0);
    lv_obj_add_style(obj_236, bg_group_25, 0);
    lv_obj_set_style_size(obj_236, lv_pct(100), 1073741823, 0);
    lv_obj_set_flex_align(obj_236, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_all(obj_236, 3, 0);
    // unnamed: label_237 (label)
    lv_obj_t* label_237 = lv_label_create(obj_236);

    lv_label_set_text(label_237, "Quick Mode:");
    lv_obj_set_style_flex_grow(label_237, 5, 0);

    // unnamed: switch_238 (switch)
    lv_obj_t* switch_238 = lv_switch_create(obj_236);

    lv_obj_set_style_height(switch_238, 20, 0);
    lv_obj_set_style_width(switch_238, 40, 0);
    lv_obj_set_style_margin_right(switch_238, 10, 0);
    data_binding_add_action(switch_238, "set_probe_quick", 1, NULL, 0, NULL);
    data_binding_add_observer("probe_quick", switch_238, 3, "value.bool", 0, NULL);






}
