#ifndef UI_GEN_UI_H
#define UI_GEN_UI_H

#include "lvgl.h"
#include "ui/assets.h"
#include "ui/components/ui_spec_helpers.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Creates the user interface as defined in the YAML specification.
 *
 * This function is automatically generated by the lvgl_ui toolchain from
 * the UI definition file. It constructs all the widgets, styles, and
 * data bindings.
 *
 * @param parent The parent lv_obj_t* onto which the UI should be created.
 *               Typically, this is the active screen (lv_screen_active()).
 */
void create_ui(lv_obj_t* parent);

#ifdef __cplusplus
}
#endif

#endif  // UI_GEN_UI_H
