; USAGE: Copy this file and rename it to platformio_override.ini
;
; The platformio_override.ini file is not overwritten or monitored by git
; ONLY edit platformio_override.ini to make local changes to the parameters

[platformio]
extra_configs =
    ; Uncomment or edit the lines to show more User Setups in the PIO sidebar
    ; config/darwin/*.ini
    ; config/esp32/*.ini
    ; config/esp32s2/*.ini
    ; config/esp32s3/*.ini
    ; config/linux/*.ini
    ; config/stm32f4xx/*.ini
    ; config/win32/*.ini

[override]
; -- Hasp config options --------------------------------------
build_flags =
; -- Uncomment the next line to use the file include/user_config_override.h settings
;    -DUSE_CONFIG_OVERRIDE

;region -- Default Build Environments : Used when Build All ---
extra_default_envs =
    ; wt32-sc01-plus_16MB
    wt32-sc01-plus_8MB
    guition-4848s040_8MB
    s3-c1-devkit-hub_8MB
;endregion

;endregion